/**
 * SGC-6 - Definições Oficiais de DDL e Políticas RLS para Supabase PostgreSQL (6º BPM - Caicó/RN)
 * Esquema unificado e sincronizado com o modelo de dados do TypeScript e Store.
 */

export const SUPABASE_FULL_SQL_SCHEMA = `-- =========================================================================
-- SGC-6: SISTEMA DE GESTÃO E CAUTELA DO 6º BPM (PMRN - CAICÓ/RN)
-- ESQUEMA COMPLETO DDL SUPABASE POSTGRESQL + INTEGRIDADE REFERENCIAL
-- =========================================================================

-- 0. EXTENSÕES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TIPOS ENUM PERSONALIZADOS
DO $$ BEGIN
    CREATE TYPE tipo_modulo AS ENUM ('Armas', 'Comunicação', 'Viaturas', 'Informática', 'Móveis e Diversos');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE modo_controle AS ENUM ('INDIVIDUAL', 'QUANTIDADE', 'HIBRIDO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE categoria_especializada AS ENUM ('ARMA', 'COLETE', 'IMPO', 'COMUNICACAO', 'VIATURA', 'INFORMATICA', 'NENHUMA');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE tipo_unidade AS ENUM ('BPM', 'CPM', 'Pelotão', 'DPM', 'Setor');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE perfil_acesso AS ENUM ('Superuser', 'P4', 'Armeiro', 'Rádio', 'Comandante');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TYPE perfil_acesso ADD VALUE IF NOT EXISTS 'Comandante';
EXCEPTION WHEN duplicate_object THEN NULL; WHEN undefined_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE condicao_item AS ENUM ('Novo', 'Bom', 'Regular', 'Manutenção', 'Inservível');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE status_item AS ENUM ('Disponível', 'Cautelado', 'Alocado', 'Manutenção', 'Baixado', 'Extraviado', 'Danificado / Avariado', 'Em apuração', 'Descarregado');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE tipo_cautela AS ENUM ('Temporária', 'Permanente');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE status_cautela AS ENUM ('Aberta', 'Finalizada', 'Atrasada', 'Cancelada');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE status_alocacao AS ENUM ('Ativa', 'Devolvida', 'Transferida');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE status_policial AS ENUM ('Ativo', 'Inativo', 'Férias', 'Licença', 'Afastado', 'Transferido');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 2. TABELA DE UNIDADES MILITARES (6º BPM E SUBUNIDADES DO SERIDÓ)
CREATE TABLE IF NOT EXISTS unidade (
    id_unidade BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(20),
    municipio VARCHAR(100) NOT NULL DEFAULT 'Caicó',
    tipo_unidade VARCHAR(30) NOT NULL DEFAULT 'BPM',
    id_unidade_superior BIGINT REFERENCES unidade(id_unidade) ON DELETE SET NULL,
    responsavel_nome VARCHAR(150),
    telefone VARCHAR(30),
    endereco TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. TABELA DE POLICIAIS MILITARES (EFETIVO)
CREATE TABLE IF NOT EXISTS policial (
    id_policial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula VARCHAR(20) NOT NULL UNIQUE,
    patente VARCHAR(30) NOT NULL,
    nome_guerra VARCHAR(50) NOT NULL,
    nome_completo VARCHAR(150) NOT NULL,
    id_unidade_lotacao BIGINT REFERENCES unidade(id_unidade) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL DEFAULT 'Ativo',
    contato VARCHAR(50),
    telefone VARCHAR(30),
    email VARCHAR(100),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. TABELA DE OPERADORES DO SISTEMA (RBAC)
CREATE TABLE IF NOT EXISTS operador_sistema (
    id_operador UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_policial BIGINT NOT NULL UNIQUE REFERENCES policial(id_policial) ON DELETE CASCADE,
    perfil_acesso VARCHAR(30) NOT NULL DEFAULT 'Armeiro',
    status VARCHAR(20) NOT NULL DEFAULT 'Ativo',
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL DEFAULT '123',
    ultimo_login TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. TABELA DE CATÁLOGO / TIPOS DE MATERIAIS
CREATE TABLE IF NOT EXISTS tipo_material (
    id_tipo_material BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    modulo VARCHAR(30) NOT NULL,
    modo_controle VARCHAR(20) NOT NULL DEFAULT 'INDIVIDUAL',
    categoria_especializada VARCHAR(30) NOT NULL DEFAULT 'NENHUMA',
    permite_marca BOOLEAN NOT NULL DEFAULT true,
    permite_modelo BOOLEAN NOT NULL DEFAULT true,
    permite_numero_serie BOOLEAN NOT NULL DEFAULT true,
    exige_numero_serie BOOLEAN NOT NULL DEFAULT false,
    permite_numero_tombo BOOLEAN NOT NULL DEFAULT true,
    exige_numero_tombo BOOLEAN NOT NULL DEFAULT false,
    permite_lote_validade BOOLEAN NOT NULL DEFAULT false,
    descricao TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'Ativo',
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. TABELA DE ITENS PATRIMONIAIS (BENS INDIVIDUAIS / CARGA SERIALIZADA)
CREATE TABLE IF NOT EXISTS item_patrimonio (
    id_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_material BIGINT REFERENCES tipo_material(id_tipo_material) ON DELETE RESTRICT,
    modulo VARCHAR(30) NOT NULL,
    tipo_item VARCHAR(100) NOT NULL,
    marca VARCHAR(50),
    modelo VARCHAR(50),
    numero_serie VARCHAR(50) UNIQUE,
    numero_tombo VARCHAR(50) UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'Disponível',
    observacao TEXT,
    data_inicio_manutencao TIMESTAMPTZ,
    motivo_manutencao TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. TABELA DE ESTOQUE / LOTES (MUNIÇÕES, COLETES, LACRES, MATERIAIS VOLUMOSOS)
CREATE TABLE IF NOT EXISTS estoque_lote (
    id_lote BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_material BIGINT REFERENCES tipo_material(id_tipo_material) ON DELETE RESTRICT,
    modulo VARCHAR(30) NOT NULL,
    tipo_item VARCHAR(100) NOT NULL,
    marca VARCHAR(50),
    modelo VARCHAR(50),
    calibre VARCHAR(20),
    lote_fabricacao VARCHAR(50),
    data_validade DATE,
    quantidade_atual INTEGER NOT NULL DEFAULT 0,
    observacao TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. TABELAS DE DETALHES POLIMÓRFICOS ESPECIALIZADOS
CREATE TABLE IF NOT EXISTS detalhe_arma (
    id_item BIGINT PRIMARY KEY REFERENCES item_patrimonio(id_item) ON DELETE CASCADE,
    calibre VARCHAR(20) NOT NULL,
    numero_sigma VARCHAR(50),
    brasao_gravado BOOLEAN NOT NULL DEFAULT true,
    qtd_carregadores INTEGER NOT NULL DEFAULT 2,
    carregadores_coincidem_numeracao BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS detalhe_colete (
    id_item BIGINT PRIMARY KEY REFERENCES item_patrimonio(id_item) ON DELETE CASCADE,
    genero VARCHAR(20) NOT NULL DEFAULT 'Masculino',
    tamanho VARCHAR(10) NOT NULL DEFAULT 'G',
    nivel_protecao VARCHAR(20) NOT NULL DEFAULT 'III-A',
    data_validade DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS detalhe_impo (
    id_item BIGINT PRIMARY KEY REFERENCES item_patrimonio(id_item) ON DELETE CASCADE,
    data_validade DATE
);

CREATE TABLE IF NOT EXISTS detalhe_comunicacao (
    id_item BIGINT PRIMARY KEY REFERENCES item_patrimonio(id_item) ON DELETE CASCADE,
    imei_mac VARCHAR(50) UNIQUE,
    numero_linha VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS detalhe_viatura (
    id_item BIGINT PRIMARY KEY REFERENCES item_patrimonio(id_item) ON DELETE CASCADE,
    placa VARCHAR(10) NOT NULL UNIQUE,
    prefixo VARCHAR(20) NOT NULL UNIQUE,
    renavam VARCHAR(30),
    chassi VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS detalhe_informatica (
    id_item BIGINT PRIMARY KEY REFERENCES item_patrimonio(id_item) ON DELETE CASCADE,
    configuracao_resumida TEXT
);

-- 9. CAUTELAS (ARMAS, COMUNICAÇÃO E MUNIÇÕES)
CREATE TABLE IF NOT EXISTS cautela (
    id_cautela BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_policial BIGINT NOT NULL REFERENCES policial(id_policial) ON DELETE RESTRICT,
    id_operador_entrega UUID NOT NULL REFERENCES operador_sistema(id_operador) ON DELETE RESTRICT,
    id_operador_devolucao UUID REFERENCES operador_sistema(id_operador) ON DELETE SET NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'Temporária',
    data_retirada TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_prevista_devolucao TIMESTAMPTZ,
    data_devolucao_efetiva TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'Aberta',
    observacao TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cautela_item (
    id_cautela BIGINT NOT NULL REFERENCES cautela(id_cautela) ON DELETE CASCADE,
    id_item BIGINT NOT NULL REFERENCES item_patrimonio(id_item) ON DELETE RESTRICT,
    observacao_estado_entrega TEXT,
    observacao_estado_devolucao TEXT,
    PRIMARY KEY (id_cautela, id_item)
);

CREATE TABLE IF NOT EXISTS cautela_estoque (
    id_cautela BIGINT NOT NULL REFERENCES cautela(id_cautela) ON DELETE CASCADE,
    id_lote BIGINT NOT NULL REFERENCES estoque_lote(id_lote) ON DELETE RESTRICT,
    quantidade INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (id_cautela, id_lote)
);

-- 10. ALOCAÇÕES DE UNIDADE (CARGA GERAL / SETORIAL)
CREATE TABLE IF NOT EXISTS alocacao_unidade (
    id_alocacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidade BIGINT NOT NULL REFERENCES unidade(id_unidade) ON DELETE RESTRICT,
    id_operador UUID NOT NULL REFERENCES operador_sistema(id_operador) ON DELETE RESTRICT,
    data_alocacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_devolucao_efetiva TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'Ativa'
);

CREATE TABLE IF NOT EXISTS alocacao_item (
    id_alocacao BIGINT NOT NULL REFERENCES alocacao_unidade(id_alocacao) ON DELETE CASCADE,
    id_item BIGINT NOT NULL REFERENCES item_patrimonio(id_item) ON DELETE RESTRICT,
    PRIMARY KEY (id_alocacao, id_item)
);

-- 11. REGISTROS ESPECIAIS DE OCORRÊNCIAS BÉLICAS
CREATE TABLE IF NOT EXISTS registro_extravio (
    id_extravio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_fato DATE NOT NULL,
    id_policial BIGINT REFERENCES policial(id_policial) ON DELETE SET NULL,
    id_cautela BIGINT REFERENCES cautela(id_cautela) ON DELETE SET NULL,
    numero_bo_ipm VARCHAR(50) NOT NULL,
    tipo_ocorrencia VARCHAR(50) NOT NULL,
    historico_circunstanciado TEXT NOT NULL,
    providencias_adotadas TEXT,
    id_operador UUID REFERENCES operador_sistema(id_operador) ON DELETE SET NULL,
    dados_itens JSONB
);

CREATE TABLE IF NOT EXISTS registro_disparo (
    id_disparo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_fato DATE NOT NULL,
    id_policial BIGINT NOT NULL REFERENCES policial(id_policial) ON DELETE RESTRICT,
    id_cautela BIGINT REFERENCES cautela(id_cautela) ON DELETE SET NULL,
    calibre VARCHAR(20) NOT NULL,
    id_lote BIGINT REFERENCES estoque_lote(id_lote) ON DELETE SET NULL,
    qtd_disparada INTEGER NOT NULL DEFAULT 1,
    qtd_reposta INTEGER NOT NULL DEFAULT 0,
    estojos_recolhidos BOOLEAN NOT NULL DEFAULT false,
    qtd_estojos_recolhidos INTEGER DEFAULT 0,
    numero_bo_ipm VARCHAR(50) NOT NULL,
    local_fato VARCHAR(150),
    historico_circunstanciado TEXT NOT NULL,
    id_operador UUID REFERENCES operador_sistema(id_operador) ON DELETE SET NULL
);

-- 12. LOGS DE AUDITORIA MILITAR DO 6º BPM
CREATE TABLE IF NOT EXISTS auditoria_sistema (
    id_auditoria BIGSERIAL PRIMARY KEY,
    id_log VARCHAR(50) NOT NULL DEFAULT gen_random_uuid()::text,
    acao VARCHAR(50) NOT NULL,
    tabela VARCHAR(50) NOT NULL,
    id_operador VARCHAR(100),
    operador_nome VARCHAR(100),
    detalhes JSONB,
    data_hora TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 13. ÍNDICES DE ALTA PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_item_modulo_status ON item_patrimonio(modulo, status);
CREATE INDEX IF NOT EXISTS idx_item_serie ON item_patrimonio(numero_serie);
CREATE INDEX IF NOT EXISTS idx_item_tombo ON item_patrimonio(numero_tombo);
CREATE INDEX IF NOT EXISTS idx_lote_modulo ON estoque_lote(modulo);
CREATE INDEX IF NOT EXISTS idx_cautela_policial ON cautela(id_policial, status);
CREATE INDEX IF NOT EXISTS idx_auditoria_data ON auditoria_sistema(data_hora DESC);
`;

export const supabaseSqlScript = SUPABASE_FULL_SQL_SCHEMA;

export const rlsPoliciesSqlScript = `-- =========================================================================
-- =========================================================================
-- SGC-6: POLÍTICAS OFICIAIS DE ROW LEVEL SECURITY (RLS) + SUPABASE REALTIME
-- Supabase PostgreSQL - 6º BPM (Caicó/RN)
-- =========================================================================

-- 1. Habilitação de RLS em todas as tabelas
ALTER TABLE IF EXISTS public.unidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.policial ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.operador_sistema ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tipo_material ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.item_patrimonio ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.estoque_lote ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_arma ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_colete ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_impo ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_comunicacao ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_viatura ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_informatica ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.alocacao_unidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.alocacao_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cautela ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cautela_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cautela_estoque ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.registro_extravio ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.registro_disparo ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.auditoria_sistema ENABLE ROW LEVEL SECURITY;

-- 2. Limpar políticas antigas para evitar duplicidade
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN (
    SELECT policyname, tablename 
    FROM pg_policies 
    WHERE schemaname = 'public'
  ) LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
  END LOOP;
END $$;

-- 3. POLÍTICAS DE AUDITORIA FORENSE (IMUTÁVEL: SOMENTE INSERT PERMITIDO)
-- Ninguém (nem mesmo administradores) pode alterar ou apagar logs de auditoria
CREATE POLICY "auditoria_select_policy" ON public.auditoria_sistema
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "auditoria_insert_only" ON public.auditoria_sistema
  FOR INSERT TO anon, authenticated WITH CHECK (true);
-- Nota: Não criar políticas de UPDATE ou DELETE para auditoria_sistema!

-- 4. POLÍTICAS DE CAUTELAS (PROTEÇÃO DE REGISTROS BÉLICOS)
-- Cautelas podem ser consultadas, abertas e atualizadas (para devolução), mas NUNCA apagadas
CREATE POLICY "cautela_select_policy" ON public.cautela
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "cautela_insert_policy" ON public.cautela
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "cautela_update_policy" ON public.cautela
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "cautela_item_all" ON public.cautela_item
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "cautela_estoque_all" ON public.cautela_estoque
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 5. POLÍTICAS PARA ITENS DO PATRIMÔNIO E DETALHES TÉCNICOS
CREATE POLICY "item_patrimonio_all" ON public.item_patrimonio
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_arma_all" ON public.detalhe_arma
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_colete_all" ON public.detalhe_colete
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_impo_all" ON public.detalhe_impo
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_comunicacao_all" ON public.detalhe_comunicacao
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_viatura_all" ON public.detalhe_viatura
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_informatica_all" ON public.detalhe_informatica
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "estoque_lote_all" ON public.estoque_lote
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 6. POLÍTICAS PARA EFETIVO, UNIDADES E OPERADORES
CREATE POLICY "policial_all" ON public.policial
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "unidade_all" ON public.unidade
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "tipo_material_all" ON public.tipo_material
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "operador_sistema_all" ON public.operador_sistema
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "alocacao_unidade_all" ON public.alocacao_unidade
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "alocacao_item_all" ON public.alocacao_item
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "registro_extravio_all" ON public.registro_extravio
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "registro_disparo_all" ON public.registro_disparo
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 7. ATIVAÇÃO DO SUPABASE REALTIME (WEBSOCKETS) EM TODAS AS TABELAS
-- Permite que mudanças em qualquer registro reflitam instantaneamente nos terminais abertos
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE 
      public.unidade,
      public.policial,
      public.operador_sistema,
      public.tipo_material,
      public.item_patrimonio,
      public.estoque_lote,
      public.detalhe_arma,
      public.detalhe_colete,
      public.detalhe_impo,
      public.detalhe_comunicacao,
      public.detalhe_viatura,
      public.detalhe_informatica,
      public.cautela,
      public.cautela_item,
      public.cautela_estoque,
      public.alocacao_unidade,
      public.alocacao_item,
      public.registro_extravio,
      public.registro_disparo,
      public.auditoria_sistema;
  EXCEPTION WHEN others THEN
    NULL;
  END;
END $$;
`;

export const enableSecureRlsAndRealtimeSqlScript = `-- =========================================================================
-- SGC-6: SCRIPT OFICIAL DE SEGURANÇA RLS + SUPABASE REALTIME (WEBSOCKETS)
-- Executar no SQL Editor do Supabase para blindar tabelas e ligar o Realtime
-- =========================================================================

-- 1. HABILITAR ROW LEVEL SECURITY (RLS) EM TODAS AS TABELAS DO 6º BPM
ALTER TABLE IF EXISTS public.unidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.policial ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.operador_sistema ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tipo_material ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.item_patrimonio ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.estoque_lote ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_arma ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_colete ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_impo ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_comunicacao ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_viatura ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_informatica ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.alocacao_unidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.alocacao_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cautela ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cautela_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cautela_estoque ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.registro_extravio ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.registro_disparo ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.auditoria_sistema ENABLE ROW LEVEL SECURITY;

-- 2. LIMPAR POLÍTICAS ANTERIORES PARA EVITAR CONFLITOS
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN (
    SELECT policyname, tablename 
    FROM pg_policies 
    WHERE schemaname = 'public'
  ) LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
  END LOOP;
END $$;

-- 3. PERMISSÕES DE ESQUEMA PARA OS PAPÉIS DO SUPABASE
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role, postgres;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role, postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role, postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

-- 4. POLÍTICAS DE AUDITORIA FORENSE (IMUTÁVEL: SOMENTE INSERT PERMITIDO)
-- Logs nunca podem ser editados nem apagados por nenhuma via da API
CREATE POLICY "auditoria_select" ON public.auditoria_sistema
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "auditoria_insert" ON public.auditoria_sistema
  FOR INSERT TO anon, authenticated WITH CHECK (true);
-- Sem política de UPDATE e sem política de DELETE: garantia de conformidade penal e militar

-- 5. POLÍTICAS DE CAUTELAS (IMPEDE EXCLUSÃO ACIDENTAL OU FRAUDULENTA)
CREATE POLICY "cautela_select" ON public.cautela
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "cautela_insert" ON public.cautela
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "cautela_update" ON public.cautela
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
-- Sem política de DELETE: cautelas são finalizadas com histórico, jamais deletadas

CREATE POLICY "cautela_item_manage" ON public.cautela_item
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "cautela_estoque_manage" ON public.cautela_estoque
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 6. POLÍTICAS PARA GESTÃO PATRIMONIAL E DETALHES TÉCNICOS
CREATE POLICY "item_patrimonio_manage" ON public.item_patrimonio
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_arma_manage" ON public.detalhe_arma
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_colete_manage" ON public.detalhe_colete
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_impo_manage" ON public.detalhe_impo
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_comunicacao_manage" ON public.detalhe_comunicacao
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_viatura_manage" ON public.detalhe_viatura
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "detalhe_informatica_manage" ON public.detalhe_informatica
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "estoque_lote_manage" ON public.estoque_lote
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 7. POLÍTICAS PARA EFETIVO, UNIDADES E OPERADORES
CREATE POLICY "policial_manage" ON public.policial
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "unidade_manage" ON public.unidade
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "tipo_material_manage" ON public.tipo_material
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "operador_sistema_manage" ON public.operador_sistema
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "alocacao_unidade_manage" ON public.alocacao_unidade
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "alocacao_item_manage" ON public.alocacao_item
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "registro_extravio_manage" ON public.registro_extravio
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "registro_disparo_manage" ON public.registro_disparo
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 8. ATIVAÇÃO DO SUPABASE REALTIME (WEBSOCKETS) PARA TODAS AS TABELAS
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE 
      public.unidade,
      public.policial,
      public.operador_sistema,
      public.tipo_material,
      public.item_patrimonio,
      public.estoque_lote,
      public.detalhe_arma,
      public.detalhe_colete,
      public.detalhe_impo,
      public.detalhe_comunicacao,
      public.detalhe_viatura,
      public.detalhe_informatica,
      public.cautela,
      public.cautela_item,
      public.cautela_estoque,
      public.alocacao_unidade,
      public.alocacao_item,
      public.registro_extravio,
      public.registro_disparo,
      public.auditoria_sistema;
  EXCEPTION WHEN others THEN
    NULL;
  END;
END $$;

-- 9. GATILHO AUTOMÁTICO: SINCRONIZAR OPERADORES COM AUTH.USERS (SUPABASE AUTH)
-- Cria ou atualiza automaticamente o usuário no cofre auth.users do Supabase
-- sem que o administrador precise cadastrar manualmente no painel do Supabase.
CREATE OR REPLACE FUNCTION public.trg_sync_operador_to_auth_users()
RETURNS TRIGGER AS $$
DECLARE
  v_encrypted_pw TEXT;
  v_user_id UUID;
  v_auth_exists BOOLEAN;
BEGIN
  IF NEW.email IS NULL OR TRIM(NEW.email) = '' THEN
    RETURN NEW;
  END IF;

  -- Gera o hash bcrypt da senha informada (padrão '123' caso não definida)
  BEGIN
    v_encrypted_pw := extensions.crypt(COALESCE(NULLIF(TRIM(NEW.senha), ''), '123'), extensions.gen_salt('bf', 10));
  EXCEPTION WHEN OTHERS THEN
    v_encrypted_pw := NULL;
  END;

  -- Verifica se já existe em auth.users
  SELECT id INTO v_user_id 
  FROM auth.users 
  WHERE LOWER(email) = LOWER(TRIM(NEW.email)) 
  LIMIT 1;

  IF v_user_id IS NULL THEN
    -- Criação automática no cofre auth.users com e-mail já confirmado
    INSERT INTO auth.users (
      id,
      instance_id,
      email,
      encrypted_password,
      email_confirmed_at,
      raw_app_meta_data,
      raw_user_meta_data,
      created_at,
      updated_at,
      role,
      aud,
      confirmation_token,
      recovery_token
    ) VALUES (
      COALESCE(NEW.id_operador, gen_random_uuid()),
      '00000000-0000-0000-0000-000000000000',
      LOWER(TRIM(NEW.email)),
      COALESCE(v_encrypted_pw, '$2a$10$abcdefghijklmnopqrstuvwxyz0123456789'),
      NOW(), -- E-mail confirmado imediatamente para uso militar
      jsonb_build_object('provider', 'email', 'providers', array['email']),
      jsonb_build_object('id_policial', NEW.id_policial, 'perfil', NEW.perfil_acesso, 'sistema', 'SGC-6 6BPM'),
      NOW(),
      NOW(),
      'authenticated',
      'authenticated',
      '',
      ''
    )
    ON CONFLICT (id) DO UPDATE SET
      email = EXCLUDED.email,
      encrypted_password = COALESCE(EXCLUDED.encrypted_password, auth.users.encrypted_password),
      updated_at = NOW();
  ELSE
    -- Atualiza a senha e metadata caso o operador tenha sido editado
    IF v_encrypted_pw IS NOT NULL THEN
      UPDATE auth.users
      SET 
        encrypted_password = v_encrypted_pw,
        email_confirmed_at = COALESCE(email_confirmed_at, NOW()),
        raw_user_meta_data = jsonb_build_object('id_policial', NEW.id_policial, 'perfil', NEW.perfil_acesso, 'sistema', 'SGC-6 6BPM'),
        updated_at = NOW()
      WHERE id = v_user_id;
    END IF;
  END IF;

  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  -- Em caso de restrição estrita de permissão de esquema, não interrompe a gravação do operador
  RAISE NOTICE 'Aviso na sincronização de auth.users: %', SQLERRM;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Ativação do gatilho na tabela operador_sistema
DROP TRIGGER IF EXISTS trg_operador_auth_sync ON public.operador_sistema;
CREATE TRIGGER trg_operador_auth_sync
AFTER INSERT OR UPDATE ON public.operador_sistema
FOR EACH ROW
EXECUTE FUNCTION public.trg_sync_operador_to_auth_users();

NOTIFY pgrst, 'reload schema';

`;

export const disableRlsSqlScript = `-- =========================================================================
-- SGC-6: SCRIPT DE LIBERAÇÃO DIRETA (MODO MATRÍCULA + SENHA PMRN)
-- Desativa o bloqueio RLS nas tabelas para permitir gravação direta via chave anon
-- Execute este script no SQL Editor do Supabase se estiver usando autenticação
-- por Matrícula e Senha sem o módulo de e-mail do Supabase Auth.
-- =========================================================================

-- Desabilitar RLS em todas as tabelas do sistema SGC-6
ALTER TABLE IF EXISTS public.unidade DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.policial DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.operador_sistema DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tipo_material DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.item_patrimonio DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.estoque_lote DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_arma DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_colete DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_impo DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_comunicacao DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_viatura DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.detalhe_informatica DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.alocacao_unidade DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.alocacao_item DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cautela DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cautela_item DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cautela_estoque DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.registro_extravio DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.registro_disparo DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.auditoria_sistema DISABLE ROW LEVEL SECURITY;

-- Garantir privilégios completos para a role anon e authenticated
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role, postgres;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role, postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role, postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

-- Inserir Unidades Estruturais do 6º BPM (Subunidades e DPMs)
INSERT INTO public.unidade (id_unidade, nome, sigla, municipio, tipo_unidade, id_unidade_superior) VALUES
(1, '6º BPM - Sede Caicó (Comando/EMG)', '6º BPM', 'Caicó', 'BPM', NULL),
(2, 'Reserva de Armamento / Sala de Meios', 'Armaria', 'Caicó', 'Setor', 1),
(3, 'Seção de Logística e Patrimônio (P4)', 'P4', 'Caicó', 'Setor', 1),
(4, 'Central de Operações e Rádio (P3/COPOM)', 'COPOM', 'Caicó', 'Setor', 1),
(10, '1ª CPM (Caicó - Sede)', '1ª CPM', 'Caicó', 'CPM', 1),
(11, 'DPM Ipueira', 'DPM Ipueira', 'Ipueira', 'DPM', 10),
(12, 'DPM São João do Sabugi', 'DPM SJ Sabugi', 'São João do Sabugi', 'DPM', 10),
(20, '2ª CPM (Jardim do Seridó - Sede)', '2ª CPM', 'Jardim do Seridó', 'CPM', 1),
(21, 'DPM Cruzeta', 'DPM Cruzeta', 'Cruzeta', 'DPM', 20),
(22, 'DPM São José do Seridó', 'DPM SJ Seridó', 'São José do Seridó', 'DPM', 20),
(23, 'DPM Ouro Branco', 'DPM Ouro Branco', 'Ouro Branco', 'DPM', 20),
(30, '3ª CPM (Jucurutu - Sede)', '3ª CPM', 'Jucurutu', 'CPM', 1),
(31, 'DPM Santana do Matos', 'DPM Santana', 'Santana do Matos', 'DPM', 30)
ON CONFLICT (id_unidade) DO UPDATE SET nome = EXCLUDED.nome;

-- Inserir Catálogo Taxonômico de Tipos de Materiais (necessário para integridade referencial)
INSERT INTO public.tipo_material (id_tipo_material, nome, modulo, modo_controle, categoria_especializada, permite_marca, permite_modelo, permite_numero_serie, exige_numero_serie, permite_numero_tombo, exige_numero_tombo, permite_lote_validade, status) VALUES
(1, 'Pistola', 'Armas', 'INDIVIDUAL', 'ARMA', true, true, true, true, true, false, false, 'Ativo'),
(2, 'Fuzil / Carabina', 'Armas', 'INDIVIDUAL', 'ARMA', true, true, true, true, true, false, false, 'Ativo'),
(3, 'Espingarda Calibre 12', 'Armas', 'INDIVIDUAL', 'ARMA', true, true, true, true, true, false, false, 'Ativo'),
(4, 'Colete Balístico', 'Armas', 'INDIVIDUAL', 'COLETE', true, true, true, false, true, false, false, 'Ativo'),
(5, 'Escudo Balístico / Choque', 'Armas', 'INDIVIDUAL', 'COLETE', true, true, true, false, true, false, false, 'Ativo'),
(6, 'Espargidor Menos Letal (IMPO)', 'Armas', 'HIBRIDO', 'IMPO', true, true, true, false, true, false, false, 'Ativo'),
(7, 'Algema de Aço / Metálica', 'Armas', 'HIBRIDO', 'NENHUMA', true, true, true, false, true, false, false, 'Ativo'),
(8, 'Munição Operacional / Treino', 'Armas', 'QUANTIDADE', 'NENHUMA', true, true, false, false, false, false, false, 'Ativo'),
(9, 'Algema Descartável / Plástica', 'Armas', 'QUANTIDADE', 'NENHUMA', true, true, false, false, false, false, false, 'Ativo'),
(10, 'Tonfa / Bastão Policial', 'Armas', 'HIBRIDO', 'NENHUMA', true, true, false, false, true, false, false, 'Ativo'),
(101, 'Arma Elétrica / Menos Letal (Spark / Taser)', 'Armas', 'INDIVIDUAL', 'NENHUMA', true, true, true, true, true, false, false, 'Ativo'),
(102, 'Cartucho / Dardo Elétrico (Spark / Taser)', 'Armas', 'QUANTIDADE', 'NENHUMA', true, true, false, false, false, false, false, 'Ativo'),
(103, 'Outro Material / Equipamento Bélico', 'Armas', 'HIBRIDO', 'NENHUMA', true, true, true, false, true, false, false, 'Ativo'),
(11, 'Rádio Portátil HT', 'Comunicação', 'INDIVIDUAL', 'COMUNICACAO', true, true, true, true, true, false, false, 'Ativo'),
(12, 'Smartphone Operacional', 'Comunicação', 'INDIVIDUAL', 'COMUNICACAO', true, true, true, true, true, false, false, 'Ativo'),
(13, 'Rádio Base Móvel VTR', 'Comunicação', 'INDIVIDUAL', 'COMUNICACAO', true, true, true, true, true, false, false, 'Ativo'),
(14, 'Bateria / Acessório de Rádio', 'Comunicação', 'HIBRIDO', 'NENHUMA', true, true, true, false, true, false, false, 'Ativo'),
(15, 'Viatura 4 Rodas (Camionete/SUV)', 'Viaturas', 'INDIVIDUAL', 'VIATURA', true, true, false, false, false, false, false, 'Ativo'),
(16, 'Motocicleta Policial', 'Viaturas', 'INDIVIDUAL', 'VIATURA', true, true, false, false, false, false, false, 'Ativo'),
(17, 'Computador Desktop / CPU', 'Informática', 'INDIVIDUAL', 'INFORMATICA', true, true, true, false, true, true, false, 'Ativo'),
(18, 'Notebook / Laptop', 'Informática', 'INDIVIDUAL', 'INFORMATICA', true, true, true, false, true, true, false, 'Ativo'),
(19, 'Monitor de Vídeo', 'Informática', 'INDIVIDUAL', 'INFORMATICA', true, true, true, false, true, true, false, 'Ativo'),
(20, 'Nobreak / Estabilizador', 'Informática', 'HIBRIDO', 'INFORMATICA', true, true, true, false, true, false, false, 'Ativo'),
(21, 'Impressora / Multifuncional', 'Informática', 'INDIVIDUAL', 'INFORMATICA', true, true, true, false, true, true, false, 'Ativo'),
(22, 'Armário Cofre / Cofre Bélico', 'Móveis e Diversos', 'INDIVIDUAL', 'NENHUMA', true, true, false, false, true, true, false, 'Ativo'),
(23, 'Mobiliário Administrativo (Mesa/Estante)', 'Móveis e Diversos', 'HIBRIDO', 'NENHUMA', true, true, false, false, true, false, false, 'Ativo'),
(24, 'Cadeira / Assento Operacional', 'Móveis e Diversos', 'HIBRIDO', 'NENHUMA', true, true, false, false, true, false, false, 'Ativo'),
(25, 'Ar Condicionado / Climatizador', 'Móveis e Diversos', 'INDIVIDUAL', 'NENHUMA', true, true, true, false, true, true, false, 'Ativo')
ON CONFLICT (id_tipo_material) DO UPDATE SET nome = EXCLUDED.nome, modulo = EXCLUDED.modulo, categoria_especializada = EXCLUDED.categoria_especializada;

-- Inserir / Atualizar o perfil do operador com seu e-mail e matrícula
INSERT INTO public.policial (id_policial, matricula, patente, nome_guerra, nome_completo, id_unidade_lotacao, status, email)
VALUES (1, 'PM-198420-1', 'Cap PM', 'Vanderson', 'Vanderson Fábio de Medeiros', 1, 'Ativo', 'vanderson.fabio@gmail.com')
ON CONFLICT (id_policial) DO UPDATE SET email = 'vanderson.fabio@gmail.com', matricula = 'PM-198420-1', nome_guerra = 'Vanderson';

-- Atualiza o operador com id_policial = 1 para seu email e senha
INSERT INTO public.operador_sistema (id_operador, id_policial, perfil_acesso, status, email, senha)
VALUES ('a0000000-0000-0000-0000-000000000001', 1, 'Superuser', 'Ativo', 'vanderson.fabio@gmail.com', 'suporte5admin')
ON CONFLICT (id_policial) DO UPDATE SET 
    email = 'vanderson.fabio@gmail.com', 
    perfil_acesso = 'Superuser', 
    status = 'Ativo', 
    senha = 'suporte5admin';

-- Sincronizar sequências numéricas IDENTITY para evitar erros de chave duplicada (23505)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'unidade_id_unidade_seq') THEN
        PERFORM setval(pg_get_serial_sequence('public.unidade', 'id_unidade'), COALESCE((SELECT MAX(id_unidade) FROM public.unidade), 1), true);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'policial_id_policial_seq') THEN
        PERFORM setval(pg_get_serial_sequence('public.policial', 'id_policial'), COALESCE((SELECT MAX(id_policial) FROM public.policial), 1), true);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'tipo_material_id_tipo_material_seq') THEN
        PERFORM setval(pg_get_serial_sequence('public.tipo_material', 'id_tipo_material'), COALESCE((SELECT MAX(id_tipo_material) FROM public.tipo_material), 1), true);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'item_patrimonio_id_item_seq') THEN
        PERFORM setval(pg_get_serial_sequence('public.item_patrimonio', 'id_item'), COALESCE((SELECT MAX(id_item) FROM public.item_patrimonio), 1), true);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'estoque_lote_id_lote_seq') THEN
        PERFORM setval(pg_get_serial_sequence('public.estoque_lote', 'id_lote'), COALESCE((SELECT MAX(id_lote) FROM public.estoque_lote), 1), true);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'cautela_id_cautela_seq') THEN
        PERFORM setval(pg_get_serial_sequence('public.cautela', 'id_cautela'), COALESCE((SELECT MAX(id_cautela) FROM public.cautela), 1), true);
    END IF;
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'alocacao_unidade_id_alocacao_seq') THEN
        PERFORM setval(pg_get_serial_sequence('public.alocacao_unidade', 'id_alocacao'), COALESCE((SELECT MAX(id_alocacao) FROM public.alocacao_unidade), 1), true);
    END IF;
END $$;

NOTIFY pgrst, 'reload schema';
`;
