import { getSupabaseClient } from './supabaseClient';
import {
  ItemPatrimonio,
  DetalheArma,
  DetalheColete,
  DetalheImpo,
  DetalheComunicacao,
  DetalheViatura,
  DetalheInformatica,
  EstoqueLote,
  Policial,
  Unidade,
  TipoMaterial,
  OperadorSistema,
  Cautela,
  CautelaItem,
  CautelaEstoque,
  AlocacaoUnidade,
  AlocacaoItem,
  AuditoriaLog,
  RegistroExtravio,
  RegistroDisparo,
} from '../types/database';

export interface SyncStatus {
  state: 'idle' | 'syncing' | 'synced' | 'error';
  lastSync?: Date;
  message?: string;
  error?: string;
}

export interface TableStats {
  unidade: number;
  policial: number;
  tipo_material: number;
  item_patrimonio: number;
  detalhe_arma: number;
  detalhe_colete: number;
  detalhe_viatura: number;
  detalhe_comunicacao: number;
  detalhe_informatica: number;
  estoque_lote: number;
  cautela: number;
  alocacao_unidade: number;
  auditoria_sistema: number;
}

export interface SyncOperationResult<T = any> {
  success: boolean;
  data?: T;
  definitiveId?: number | string;
  error?: string;
  code?: string;
  details?: string;
  hint?: string;
}

export interface SyncEntityResult {
  entity: string;
  success: boolean;
  processed: number;
  errors: number;
  message?: string;
  errorCode?: string;
  errorDetails?: string;
}

export interface FullSyncResult {
  success: boolean;
  message: string;
  results: SyncEntityResult[];
  error?: string;
}

/**
 * Pushes a single item and its specialized details (e.g. Arma, Colete, VTR) to Supabase.
 * - DOES NOT send identity id_item on INSERT.
 * - Extracts definitive id_item generated by PostgreSQL.
 * - Uses definitive id_item for inserting/upserting specialized details (detalhe_arma, etc.).
 * - Verifies and resolves foreign key id_tipo_material without guessing.
 */
export async function pushItemToSupabase(
  item: ItemPatrimonio,
  detalhes?: {
    arma?: DetalheArma;
    colete?: DetalheColete;
    impo?: DetalheImpo;
    comunicacao?: DetalheComunicacao;
    viatura?: DetalheViatura;
    informatica?: DetalheInformatica;
  },
  tipoMaterial?: TipoMaterial
): Promise<SyncOperationResult<{ id_item: number }>> {
  const client = getSupabaseClient();
  if (!client) {
    return { success: false, error: 'Supabase não conectado. Configure as credenciais do projeto.' };
  }

  try {
    // 1. Resolve Foreign Key: id_tipo_material
    let resolvedTipoId: number | null = null;

    if (item.id_tipo_material) {
      // Verify if specified id_tipo_material exists in Supabase
      const { data: tipoRow } = await client
        .from('tipo_material')
        .select('id_tipo_material')
        .eq('id_tipo_material', item.id_tipo_material)
        .maybeSingle();

      if (tipoRow?.id_tipo_material) {
        resolvedTipoId = Number(tipoRow.id_tipo_material);
      }
    }

    // If not resolved by ID, attempt lookup by natural key: nome
    if (!resolvedTipoId && item.tipo_item) {
      const { data: tipoByName } = await client
        .from('tipo_material')
        .select('id_tipo_material')
        .ilike('nome', item.tipo_item.trim())
        .maybeSingle();

      if (tipoByName?.id_tipo_material) {
        resolvedTipoId = Number(tipoByName.id_tipo_material);
      }
    }

    // If tipoMaterial payload was explicitly provided and still not in DB, insert it first
    if (!resolvedTipoId && tipoMaterial) {
      const tipoRes = await pushTipoMaterialToSupabase(tipoMaterial);
      if (tipoRes.success && tipoRes.definitiveId) {
        resolvedTipoId = Number(tipoRes.definitiveId);
      }
    }

    // If id_tipo_material could not be resolved and is required by schema integrity
    if (!resolvedTipoId && item.id_tipo_material) {
      const msg = `Tipo de material referenciado (ID: ${item.id_tipo_material}, Nome: "${item.tipo_item}") não foi encontrado no banco Supabase. Cadastre ou sincronize o catálogo de materiais primeiro.`;
      console.error('[Supabase] Falha de Chave Estrangeira:', msg);
      return { success: false, error: msg };
    }

    // 2. Check if item already exists in Supabase by natural unique keys (numero_serie or numero_tombo)
    let existingDbId: number | null = null;

    if (item.numero_serie && item.numero_serie.trim()) {
      const { data: existingBySerie } = await client
        .from('item_patrimonio')
        .select('id_item')
        .eq('numero_serie', item.numero_serie.trim())
        .maybeSingle();

      if (existingBySerie?.id_item) {
        existingDbId = Number(existingBySerie.id_item);
      }
    }

    if (!existingDbId && item.numero_tombo && item.numero_tombo.trim()) {
      const { data: existingByTombo } = await client
        .from('item_patrimonio')
        .select('id_item')
        .eq('numero_tombo', item.numero_tombo.trim())
        .maybeSingle();

      if (existingByTombo?.id_item) {
        existingDbId = Number(existingByTombo.id_item);
      }
    }

    let definitiveId: number;

    const basePayload = {
      id_tipo_material: resolvedTipoId || null,
      modulo: item.modulo,
      tipo_item: item.tipo_item,
      marca: item.marca || null,
      modelo: item.modelo || null,
      numero_serie: item.numero_serie || null,
      numero_tombo: item.numero_tombo || null,
      status: item.status,
      observacao: item.observacao || null,
    };

    if (existingDbId) {
      // UPDATE existing item (DO NOT pass id_item in update body)
      const { data: updatedItem, error: updateErr } = await client
        .from('item_patrimonio')
        .update(basePayload)
        .eq('id_item', existingDbId)
        .select()
        .single();

      if (updateErr) {
        console.error('[Supabase] Falha ao atualizar item_patrimonio:', updateErr);
        return {
          success: false,
          error: `Falha ao atualizar item no Supabase: ${updateErr.message}`,
          code: updateErr.code,
          details: updateErr.details,
          hint: updateErr.hint,
        };
      }
      definitiveId = Number(updatedItem.id_item);
    } else {
      // INSERT new item (PostgreSQL IDENTITY will generate the ID)
      const { data: insertedItem, error: insertErr } = await client
        .from('item_patrimonio')
        .insert(basePayload)
        .select()
        .single();

      if (insertErr) {
        console.error('[Supabase] Falha ao inserir item_patrimonio:', insertErr);
        return {
          success: false,
          error: `Falha ao inserir item no Supabase: ${insertErr.message}`,
          code: insertErr.code,
          details: insertErr.details,
          hint: insertErr.hint,
        };
      }

      if (!insertedItem?.id_item) {
        const msg = 'PostgreSQL não retornou o id_item gerado após a inserção.';
        console.error('[Supabase] Erro de retorno:', msg);
        return { success: false, error: msg };
      }

      definitiveId = Number(insertedItem.id_item);
    }

    // 3. Upsert specialized details using the DEFINITIVE id_item
    if (detalhes?.arma) {
      const { error: armaErr } = await client.from('detalhe_arma').upsert({
        id_item: definitiveId,
        calibre: detalhes.arma.calibre,
        numero_sigma: detalhes.arma.numero_sigma || null,
        brasao_gravado: detalhes.arma.brasao_gravado ?? true,
        qtd_carregadores: detalhes.arma.qtd_carregadores ?? 2,
        carregadores_coincidem_numeracao: detalhes.arma.carregadores_coincidem_numeracao ?? false,
      }, { onConflict: 'id_item' });

      if (armaErr) {
        console.error('[Supabase] Falha ao persistir detalhe_arma:', armaErr);
        return {
          success: false,
          error: `Falha ao persistir especificações da arma: ${armaErr.message}`,
          code: armaErr.code,
          details: armaErr.details,
          hint: armaErr.hint,
        };
      }
    }

    if (detalhes?.colete) {
      const { error: colErr } = await client.from('detalhe_colete').upsert({
        id_item: definitiveId,
        genero: detalhes.colete.genero || 'Masculino',
        tamanho: detalhes.colete.tamanho || 'G',
        nivel_protecao: detalhes.colete.nivel_protecao || 'III-A',
        data_validade: detalhes.colete.data_validade,
      }, { onConflict: 'id_item' });

      if (colErr) {
        console.error('[Supabase] Falha ao persistir detalhe_colete:', colErr);
        return { success: false, error: `Falha ao persistir colete: ${colErr.message}` };
      }
    }

    if (detalhes?.impo) {
      const { error: impoErr } = await client.from('detalhe_impo').upsert({
        id_item: definitiveId,
        data_validade: detalhes.impo.data_validade || null,
      }, { onConflict: 'id_item' });

      if (impoErr) {
        console.error('[Supabase] Falha ao persistir detalhe_impo:', impoErr);
        return { success: false, error: `Falha ao persistir IMPO: ${impoErr.message}` };
      }
    }

    if (detalhes?.comunicacao) {
      const { error: comErr } = await client.from('detalhe_comunicacao').upsert({
        id_item: definitiveId,
        imei_mac: detalhes.comunicacao.imei_mac || null,
        numero_linha: detalhes.comunicacao.numero_linha || null,
      }, { onConflict: 'id_item' });

      if (comErr) {
        console.error('[Supabase] Falha ao persistir detalhe_comunicacao:', comErr);
        return { success: false, error: `Falha ao persistir equipamento de comunicação: ${comErr.message}` };
      }
    }

    if (detalhes?.viatura) {
      const safePlaca = (detalhes.viatura.placa || `PMR-${definitiveId}`).trim().toUpperCase();
      const safePrefixo = (detalhes.viatura.prefixo?.trim() || `VTR-${safePlaca.replace(/[^a-zA-Z0-9]/g, '')}`).toUpperCase();
      const { error: vtrErr } = await client.from('detalhe_viatura').upsert({
        id_item: definitiveId,
        placa: safePlaca,
        prefixo: safePrefixo,
        renavam: detalhes.viatura.renavam?.trim() || null,
        chassi: detalhes.viatura.chassi?.trim() || null,
      }, { onConflict: 'id_item' });

      if (vtrErr) {
        console.error('[Supabase] Falha ao persistir detalhe_viatura:', vtrErr);
        return { success: false, error: `Falha ao persistir viatura: ${vtrErr.message}` };
      }
    }

    if (detalhes?.informatica) {
      const { error: infErr } = await client.from('detalhe_informatica').upsert({
        id_item: definitiveId,
        configuracao_resumida: detalhes.informatica.configuracao_resumida || null,
      }, { onConflict: 'id_item' });

      if (infErr) {
        console.error('[Supabase] Falha ao persistir detalhe_informatica:', infErr);
        return { success: false, error: `Falha ao persistir TI: ${infErr.message}` };
      }
    }

    return {
      success: true,
      data: { id_item: definitiveId },
      definitiveId,
    };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao persistir item:', err);
    return {
      success: false,
      error: err.message || 'Exceção não tratada na gravação do item.',
    };
  }
}

/**
 * Deletes an item from Supabase (cascades to detalhe_*).
 */
export async function deleteItemFromSupabase(id_item: number): Promise<SyncOperationResult> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const { error } = await client.from('item_patrimonio').delete().eq('id_item', id_item);
    if (error) {
      console.error('[Supabase] Falha ao excluir item_patrimonio:', error);
      return { success: false, error: error.message, code: error.code, details: error.details };
    }
    return { success: true };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao excluir item:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Pushes a Policial to Supabase.
 * - Uses matricula and id_policial as lookups.
 * - Does not send id_policial on INSERT.
 * - Validates id_unidade_lotacao.
 */
export async function pushPolicialToSupabase(policial: Policial): Promise<SyncOperationResult<{ id_policial: number }>> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    // 1. Resolve unit foreign key (id_unidade_lotacao / id_unidade)
    let resolvedUnidadeId: number | null = null;
    const targetUnitId = policial.id_unidade_lotacao || policial.id_unidade;

    if (targetUnitId) {
      resolvedUnidadeId = Number(targetUnitId);
      // Verify that this unit exists in database
      const { data: unitRow } = await client
        .from('unidade')
        .select('id_unidade')
        .eq('id_unidade', resolvedUnidadeId)
        .maybeSingle();

      if (!unitRow?.id_unidade) {
        // If not found by ID, fallback to first unit in database
        const { data: firstUnit } = await client
          .from('unidade')
          .select('id_unidade')
          .order('id_unidade', { ascending: true })
          .limit(1)
          .maybeSingle();

        resolvedUnidadeId = firstUnit?.id_unidade ? Number(firstUnit.id_unidade) : null;
      }
    } else {
      const { data: firstUnit } = await client
        .from('unidade')
        .select('id_unidade')
        .order('id_unidade', { ascending: true })
        .limit(1)
        .maybeSingle();

      resolvedUnidadeId = firstUnit?.id_unidade ? Number(firstUnit.id_unidade) : null;
    }

    // 2. Check if policial already exists by id_policial OR by matricula
    let existingDbId: number | null = null;

    if (policial.id_policial) {
      const { data: existingById } = await client
        .from('policial')
        .select('id_policial')
        .eq('id_policial', policial.id_policial)
        .maybeSingle();
      if (existingById?.id_policial) {
        existingDbId = Number(existingById.id_policial);
      }
    }

    if (!existingDbId && policial.matricula && policial.matricula.trim()) {
      const { data: existingPol } = await client
        .from('policial')
        .select('id_policial')
        .eq('matricula', policial.matricula.trim())
        .maybeSingle();
      if (existingPol?.id_policial) {
        existingDbId = Number(existingPol.id_policial);
      }
    }

    const payload = {
      matricula: policial.matricula.trim(),
      patente: policial.patente,
      nome_guerra: policial.nome_guerra,
      nome_completo: policial.nome_completo,
      id_unidade_lotacao: resolvedUnidadeId,
      status: policial.status,
      contato: policial.contato || null,
      telefone: policial.telefone || null,
      email: policial.email || null,
    };

    let definitiveId: number;

    if (existingDbId) {
      // UPDATE
      const { data: updated, error: updateErr } = await client
        .from('policial')
        .update(payload)
        .eq('id_policial', existingDbId)
        .select()
        .single();

      if (updateErr) {
        console.error('[Supabase] Falha ao atualizar policial:', updateErr);
        return { success: false, error: updateErr.message, code: updateErr.code, details: updateErr.details };
      }
      definitiveId = Number(updated.id_policial);
    } else {
      // INSERT (without id_policial)
      const { data: inserted, error: insertErr } = await client
        .from('policial')
        .insert(payload)
        .select()
        .single();

      if (insertErr) {
        // If failed due to duplicate key (e.g. sequence collision or unique matricula)
        if (insertErr.code === '23505') {
          const { data: retryPol } = await client
            .from('policial')
            .select('id_policial')
            .eq('matricula', policial.matricula.trim())
            .maybeSingle();

          if (retryPol?.id_policial) {
            const { data: updatedRetry, error: retryUpdErr } = await client
              .from('policial')
              .update(payload)
              .eq('id_policial', retryPol.id_policial)
              .select()
              .single();

            if (!retryUpdErr && updatedRetry?.id_policial) {
              return {
                success: true,
                data: { id_policial: Number(updatedRetry.id_policial) },
                definitiveId: Number(updatedRetry.id_policial),
              };
            }
          }
        }
        console.error('[Supabase] Falha ao inserir policial:', insertErr);
        return { success: false, error: insertErr.message, code: insertErr.code, details: insertErr.details };
      }
      definitiveId = Number(inserted.id_policial);
    }

    return {
      success: true,
      data: { id_policial: definitiveId },
      definitiveId,
    };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao persistir policial:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Pushes an Operador do Sistema to Supabase.
 * - Handles FK resolution with policial table.
 * - Upserts safely by id_policial, email, or id_operador to prevent 23505 duplicate key errors.
 */
export async function pushOperadorToSupabase(
  op: OperadorSistema,
  mappedPolicialId?: number
): Promise<SyncOperationResult<{ id_operador: string }>> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const targetPolicialId = mappedPolicialId || op.id_policial;

    // 1. Verify that target policial exists in Supabase
    const { data: polRow } = await client
      .from('policial')
      .select('id_policial')
      .eq('id_policial', targetPolicialId)
      .maybeSingle();

    if (!polRow?.id_policial) {
      const msg = `Policial com ID ${targetPolicialId} não encontrado no Supabase para vincular ao operador ${op.email}.`;
      console.warn('[Supabase] Aviso de FK em operador:', msg);
      return { success: false, error: msg };
    }

    const safePolicialId = Number(polRow.id_policial);
    const safeEmail = (op.email && op.email.trim()) || `operador_${safePolicialId}@pm.rn.gov.br`;

    // 2. Check for existing operador by id_policial, email, or id_operador
    let existingDbOp: any = null;

    const { data: byPol } = await client
      .from('operador_sistema')
      .select('*')
      .eq('id_policial', safePolicialId)
      .maybeSingle();

    if (byPol) {
      existingDbOp = byPol;
    } else {
      const { data: byEmail } = await client
        .from('operador_sistema')
        .select('*')
        .ilike('email', safeEmail)
        .maybeSingle();

      if (byEmail) {
        existingDbOp = byEmail;
      } else if (op.id_operador) {
        const { data: byId } = await client
          .from('operador_sistema')
          .select('*')
          .eq('id_operador', op.id_operador)
          .maybeSingle();

        if (byId) {
          existingDbOp = byId;
        }
      }
    }

    if (existingDbOp) {
      // UPDATE
      const { data: updated, error: updErr } = await client
        .from('operador_sistema')
        .update({
          id_policial: safePolicialId,
          perfil_acesso: op.perfil_acesso,
          status: op.status,
          email: safeEmail,
          senha: op.senha || existingDbOp.senha || '123',
        })
        .eq('id_operador', existingDbOp.id_operador)
        .select()
        .single();

      if (updErr) {
        console.error('[Supabase] Falha ao atualizar operador_sistema:', updErr);
        return { success: false, error: updErr.message, code: updErr.code };
      }

      // Auto-sync credentials with Supabase Auth (auth.users)
      syncOperadorAuthUser(safeEmail, op.senha || existingDbOp.senha || '123', {
        id_policial: safePolicialId,
        perfil: op.perfil_acesso,
      }).catch(() => {});

      return {
        success: true,
        data: { id_operador: updated.id_operador },
        definitiveId: updated.id_operador,
      };
    } else {
      // INSERT
      const insertPayload: any = {
        id_policial: safePolicialId,
        perfil_acesso: op.perfil_acesso,
        status: op.status,
        email: safeEmail,
        senha: op.senha || '123',
      };
      if (op.id_operador) {
        insertPayload.id_operador = op.id_operador;
      }

      const { data: inserted, error: insErr } = await client
        .from('operador_sistema')
        .insert(insertPayload)
        .select()
        .single();

      if (insErr) {
        console.error('[Supabase] Falha ao inserir operador_sistema:', insErr);
        return { success: false, error: insErr.message, code: insErr.code };
      }

      // Auto-sync credentials with Supabase Auth (auth.users)
      syncOperadorAuthUser(safeEmail, op.senha || '123', {
        id_policial: safePolicialId,
        perfil: op.perfil_acesso,
      }).catch(() => {});

      return {
        success: true,
        data: { id_operador: inserted.id_operador },
        definitiveId: inserted.id_operador,
      };
    }
  } catch (err: any) {
    console.error('[Supabase] Exceção ao persistir operador:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Auto-provisions or syncs the user in Supabase Auth (auth.users)
 * so the operator can log in seamlessly with JWT tokens under RLS.
 */
export async function syncOperadorAuthUser(
  email: string,
  senha?: string,
  metadata?: { id_policial?: number; perfil?: string }
): Promise<{ success: boolean; error?: string }> {
  const client = getSupabaseClient();
  if (!client || !email) return { success: false, error: 'Supabase não conectado' };

  try {
    const safeEmail = email.trim().toLowerCase();
    const safePassword = senha?.trim() || '123';

    // 1. Attempt signUp on Supabase Auth
    const { data, error: signUpErr } = await client.auth.signUp({
      email: safeEmail,
      password: safePassword,
      options: {
        data: {
          id_policial: metadata?.id_policial,
          perfil: metadata?.perfil,
          origem: 'SGC-6 6º BPM',
        },
      },
    });

    if (!signUpErr) {
      console.log(`[Supabase Auth] Usuário '${safeEmail}' provisionado com sucesso em auth.users.`);
      return { success: true };
    }

    // 2. If user already registered in auth.users, that's fine
    if (
      signUpErr.message?.toLowerCase().includes('already registered') ||
      signUpErr.message?.toLowerCase().includes('already exists') ||
      signUpErr.status === 422
    ) {
      return { success: true };
    }

    console.warn(`[Supabase Auth] Aviso ao provisionar '${safeEmail}':`, signUpErr.message);
    return { success: false, error: signUpErr.message };
  } catch (err: any) {
    console.warn('[Supabase Auth] Exceção ao sincronizar credenciais:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Bulk syncs all operators to Supabase Auth.
 */
export async function syncAllOperadoresToAuth(
  operadores: OperadorSistema[],
  policiais: Policial[]
): Promise<{ success: boolean; count: number; errors: string[] }> {
  const errors: string[] = [];
  let count = 0;

  for (const op of operadores) {
    if (!op.email) continue;
    const pol = policiais.find((p) => p.id_policial === op.id_policial);
    const res = await syncOperadorAuthUser(op.email, op.senha, {
      id_policial: op.id_policial,
      perfil: op.perfil_acesso,
    });
    if (res.success) {
      count++;
    } else if (res.error) {
      errors.push(`${pol ? pol.nome_guerra : op.email}: ${res.error}`);
    }
  }

  return { success: errors.length === 0, count, errors };
}

/**
 * Deletes an Operador do Sistema from Supabase.
 */
export async function deleteOperadorFromSupabase(id_operador: string): Promise<SyncOperationResult> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const { error } = await client
      .from('operador_sistema')
      .delete()
      .eq('id_operador', id_operador);

    if (error) {
      console.error('[Supabase] Falha ao excluir operador_sistema:', error);
      return { success: false, error: error.message, code: error.code };
    }
    return { success: true };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao excluir operador_sistema:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Pushes a TipoMaterial to Supabase.
 * - Uses nome as natural unique key.
 * - Does not send id_tipo_material on INSERT.
 */
export async function pushTipoMaterialToSupabase(tipo: TipoMaterial): Promise<SyncOperationResult<{ id_tipo_material: number }>> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const { data: existing } = await client
      .from('tipo_material')
      .select('id_tipo_material')
      .ilike('nome', tipo.nome.trim())
      .maybeSingle();

    const payload = {
      nome: tipo.nome.trim(),
      modulo: tipo.modulo,
      modo_controle: tipo.modo_controle,
      categoria_especializada: tipo.categoria_especializada,
      permite_marca: tipo.permite_marca,
      permite_modelo: tipo.permite_modelo,
      permite_numero_serie: tipo.permite_numero_serie,
      exige_numero_serie: tipo.exige_numero_serie,
      permite_numero_tombo: tipo.permite_numero_tombo,
      exige_numero_tombo: tipo.exige_numero_tombo,
      permite_lote_validade: tipo.permite_lote_validade,
      descricao: tipo.descricao || null,
      status: tipo.status,
    };

    let definitiveId: number;

    if (existing?.id_tipo_material) {
      const { data: updated, error: updateErr } = await client
        .from('tipo_material')
        .update(payload)
        .eq('id_tipo_material', existing.id_tipo_material)
        .select()
        .single();

      if (updateErr) {
        console.error('[Supabase] Falha ao atualizar tipo_material:', updateErr);
        return { success: false, error: updateErr.message, code: updateErr.code };
      }
      definitiveId = Number(updated.id_tipo_material);
    } else {
      const { data: inserted, error: insertErr } = await client
        .from('tipo_material')
        .insert(payload)
        .select()
        .single();

      if (insertErr) {
        console.error('[Supabase] Falha ao inserir tipo_material:', insertErr);
        return { success: false, error: insertErr.message, code: insertErr.code };
      }
      definitiveId = Number(inserted.id_tipo_material);
    }

    return {
      success: true,
      data: { id_tipo_material: definitiveId },
      definitiveId,
    };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao persistir tipo_material:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Pushes an Unidade to Supabase.
 * - Checks by id_unidade first, then falls back to nome.
 * - Performs UPDATE if found, or INSERT if new.
 */
export async function pushUnidadeToSupabase(unidade: Unidade): Promise<SyncOperationResult<{ id_unidade: number }>> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    let existingDbId: number | null = null;

    if (unidade.id_unidade) {
      const { data: byId } = await client
        .from('unidade')
        .select('id_unidade')
        .eq('id_unidade', unidade.id_unidade)
        .maybeSingle();
      if (byId?.id_unidade) {
        existingDbId = Number(byId.id_unidade);
      }
    }

    if (!existingDbId && unidade.nome && unidade.nome.trim()) {
      const { data: byNome } = await client
        .from('unidade')
        .select('id_unidade')
        .ilike('nome', unidade.nome.trim())
        .maybeSingle();
      if (byNome?.id_unidade) {
        existingDbId = Number(byNome.id_unidade);
      }
    }

    const payload = {
      nome: unidade.nome.trim(),
      sigla: unidade.sigla || null,
      municipio: unidade.municipio || 'Caicó',
      tipo_unidade: unidade.tipo_unidade,
      id_unidade_superior: unidade.id_unidade_superior || null,
      responsavel_nome: unidade.responsavel_nome || null,
      telefone: unidade.telefone || null,
      endereco: unidade.endereco || null,
    };

    let definitiveId: number;

    if (existingDbId) {
      const { data: updated, error: updateErr } = await client
        .from('unidade')
        .update(payload)
        .eq('id_unidade', existingDbId)
        .select()
        .single();

      if (updateErr) {
        console.error('[Supabase] Falha ao atualizar unidade:', updateErr);
        return { success: false, error: updateErr.message, code: updateErr.code };
      }
      definitiveId = Number(updated.id_unidade);
    } else {
      const { data: inserted, error: insertErr } = await client
        .from('unidade')
        .insert(payload)
        .select()
        .single();

      if (insertErr) {
        console.error('[Supabase] Falha ao inserir unidade:', insertErr);
        return { success: false, error: insertErr.message, code: insertErr.code };
      }
      definitiveId = Number(inserted.id_unidade);
    }

    return {
      success: true,
      data: { id_unidade: definitiveId },
      definitiveId,
    };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao persistir unidade:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Deletes an Unidade from Supabase.
 */
export async function deleteUnidadeFromSupabase(id_unidade: number): Promise<SyncOperationResult> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const { error } = await client
      .from('unidade')
      .delete()
      .eq('id_unidade', id_unidade);

    if (error) {
      console.error('[Supabase] Falha ao excluir unidade:', error);
      return { success: false, error: error.message, code: error.code };
    }
    return { success: true };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao excluir unidade:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Pushes a batch or single lote (munições, volumes) to Supabase.
 * - Checks by primary id_lote first, then falls back to composite keys.
 * - Extracts definitive id_lote generated by PostgreSQL.
 */
export async function pushLoteToSupabase(lote: EstoqueLote): Promise<SyncOperationResult<{ id_lote: number }>> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    // 1. Resolve tipo_material
    let resolvedTipoId: number | null = null;
    if (lote.id_tipo_material) {
      const { data: tipoRow } = await client
        .from('tipo_material')
        .select('id_tipo_material')
        .eq('id_tipo_material', lote.id_tipo_material)
        .maybeSingle();

      if (tipoRow?.id_tipo_material) {
        resolvedTipoId = Number(tipoRow.id_tipo_material);
      }
    }

    if (!resolvedTipoId && lote.tipo_item) {
      const { data: tipoByName } = await client
        .from('tipo_material')
        .select('id_tipo_material')
        .ilike('nome', lote.tipo_item.trim())
        .maybeSingle();

      if (tipoByName?.id_tipo_material) {
        resolvedTipoId = Number(tipoByName.id_tipo_material);
      }
    }

    // 2. Check for existing lote: first by id_lote, then by composite keys
    let existingDbId: number | null = null;
    if (lote.id_lote) {
      const { data: byId } = await client
        .from('estoque_lote')
        .select('id_lote')
        .eq('id_lote', lote.id_lote)
        .maybeSingle();
      if (byId?.id_lote) {
        existingDbId = Number(byId.id_lote);
      }
    }

    if (!existingDbId) {
      let existingQuery = client.from('estoque_lote').select('id_lote').eq('tipo_item', lote.tipo_item);
      if (lote.calibre) existingQuery = existingQuery.eq('calibre', lote.calibre);
      if (lote.lote_fabricacao) existingQuery = existingQuery.eq('lote_fabricacao', lote.lote_fabricacao);

      const { data: existingLote } = await existingQuery.maybeSingle();
      if (existingLote?.id_lote) {
        existingDbId = Number(existingLote.id_lote);
      }
    }

    const payload = {
      id_tipo_material: resolvedTipoId,
      modulo: lote.modulo,
      tipo_item: lote.tipo_item,
      marca: lote.marca || null,
      modelo: lote.modelo || null,
      calibre: lote.calibre || null,
      lote_fabricacao: lote.lote_fabricacao || null,
      data_validade: lote.data_validade || null,
      quantidade_atual: Math.max(0, lote.quantidade_atual),
      observacao: lote.observacao || null,
    };

    let definitiveId: number;

    if (existingDbId) {
      const { data: updated, error: updateErr } = await client
        .from('estoque_lote')
        .update(payload)
        .eq('id_lote', existingDbId)
        .select()
        .single();

      if (updateErr) {
        console.error('[Supabase] Falha ao atualizar estoque_lote:', updateErr);
        return { success: false, error: updateErr.message, code: updateErr.code };
      }
      definitiveId = Number(updated.id_lote);
    } else {
      const { data: inserted, error: insertErr } = await client
        .from('estoque_lote')
        .insert(payload)
        .select()
        .single();

      if (insertErr) {
        console.error('[Supabase] Falha ao inserir estoque_lote:', insertErr);
        return { success: false, error: insertErr.message, code: insertErr.code };
      }
      definitiveId = Number(inserted.id_lote);
    }

    return {
      success: true,
      data: { id_lote: definitiveId },
      definitiveId,
    };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao persistir lote:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Updates quantity of an inventory lote directly in Supabase.
 */
export async function updateLoteQuantidadeInSupabase(
  id_lote: number,
  novaQuantidade: number
): Promise<SyncOperationResult> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const { error } = await client
      .from('estoque_lote')
      .update({ quantidade_atual: Math.max(0, novaQuantidade) })
      .eq('id_lote', id_lote);

    if (error) {
      console.error('[Supabase] Falha ao atualizar quantidade do lote:', error);
      return { success: false, error: error.message, code: error.code };
    }
    return { success: true };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao atualizar quantidade do lote:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Updates status and note of a single item directly in Supabase.
 */
export async function updateItemStatusInSupabase(
  id_item: number,
  status: string,
  observacao?: string
): Promise<SyncOperationResult> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const payload: any = { status };
    if (observacao !== undefined) payload.observacao = observacao;

    const { error } = await client
      .from('item_patrimonio')
      .update(payload)
      .eq('id_item', id_item);

    if (error) {
      console.error('[Supabase] Falha ao atualizar status do item:', error);
      return { success: false, error: error.message, code: error.code };
    }
    return { success: true };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao atualizar status do item:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Pushes a Cautela and its items/lotes to Supabase.
 * - Inserts or updates Cautela.
 * - Extracts definitive id_cautela and inserts into cautela_item and cautela_estoque.
 * - Updates item_patrimonio status to 'Cautelado'.
 * - Synchronizes deducted stock on estoque_lote.
 */
export async function pushCautelaToSupabase(
  cautela: Cautela,
  itens: CautelaItem[] = [],
  lotes: CautelaEstoque[] = [],
  lotesSaldosRestantes?: Array<{ id_lote: number; quantidade_atual: number }>
): Promise<SyncOperationResult<{ id_cautela: number }>> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    // 1. Validate Policial Foreign Key
    const { data: polRow } = await client
      .from('policial')
      .select('id_policial')
      .eq('id_policial', cautela.id_policial)
      .maybeSingle();

    if (!polRow) {
      const msg = `Policial de destino (ID: ${cautela.id_policial}) não existe no Supabase. Sincronize o efetivo primeiro.`;
      console.error('[Supabase] Falha de FK:', msg);
      return { success: false, error: msg };
    }

    // 2. Check if Cautela already exists
    let existingCautelaId: number | null = null;
    if (cautela.id_cautela) {
      const { data: cCheck } = await client
        .from('cautela')
        .select('id_cautela')
        .eq('id_cautela', cautela.id_cautela)
        .maybeSingle();
      if (cCheck?.id_cautela) {
        existingCautelaId = Number(cCheck.id_cautela);
      }
    }

    const payload = {
      id_policial: Number(polRow.id_policial),
      id_operador_entrega: cautela.id_operador_entrega,
      id_operador_devolucao: cautela.id_operador_devolucao || null,
      tipo: cautela.tipo,
      data_retirada: cautela.data_retirada,
      data_prevista_devolucao: cautela.data_prevista_devolucao || null,
      data_devolucao_efetiva: cautela.data_devolucao_efetiva || null,
      status: cautela.status,
      observacao: cautela.observacao || null,
    };

    let definitiveCautelaId: number;

    if (existingCautelaId) {
      const { data: updatedCautela, error: uErr } = await client
        .from('cautela')
        .update(payload)
        .eq('id_cautela', existingCautelaId)
        .select()
        .single();

      if (uErr) {
        console.error('[Supabase] Falha ao atualizar cautela:', uErr);
        return { success: false, error: uErr.message, code: uErr.code };
      }
      definitiveCautelaId = Number(updatedCautela.id_cautela);
    } else {
      const { data: insertedCautela, error: cErr } = await client
        .from('cautela')
        .insert(payload)
        .select()
        .single();

      if (cErr) {
        console.error('[Supabase] Falha ao inserir cautela:', cErr);
        return {
          success: false,
          error: `Falha ao registrar cautela no Supabase: ${cErr.message}`,
          code: cErr.code,
          details: cErr.details,
        };
      }
      definitiveCautelaId = Number(insertedCautela.id_cautela);
    }

    // 3. Insert items links and update item_patrimonio status to 'Cautelado'
    for (const itemLink of itens) {
      const { data: itemRow } = await client
        .from('item_patrimonio')
        .select('id_item')
        .eq('id_item', itemLink.id_item)
        .maybeSingle();

      if (itemRow?.id_item) {
        await client.from('cautela_item').upsert({
          id_cautela: definitiveCautelaId,
          id_item: Number(itemRow.id_item),
          observacao_estado_entrega: itemLink.observacao_estado_entrega || null,
          observacao_estado_devolucao: itemLink.observacao_estado_devolucao || null,
        }, { onConflict: 'id_cautela,id_item' });

        // Update item status in Supabase
        const targetStatus = cautela.status === 'Finalizada' ? 'Disponível' : 'Cautelado';
        await client
          .from('item_patrimonio')
          .update({ status: targetStatus })
          .eq('id_item', Number(itemRow.id_item));
      }
    }

    // 4. Insert lotes links and update estoque_lote stock
    for (const loteLink of lotes) {
      const { data: loteRow } = await client
        .from('estoque_lote')
        .select('id_lote, quantidade_atual')
        .eq('id_lote', loteLink.id_lote)
        .maybeSingle();

      if (loteRow?.id_lote) {
        await client.from('cautela_estoque').upsert({
          id_cautela: definitiveCautelaId,
          id_lote: Number(loteRow.id_lote),
          quantidade: loteLink.quantidade,
        }, { onConflict: 'id_cautela,id_lote' });

        // Update remaining stock in Supabase
        if (lotesSaldosRestantes && lotesSaldosRestantes.length > 0) {
          const spec = lotesSaldosRestantes.find((s) => s.id_lote === loteLink.id_lote);
          if (spec) {
            await client
              .from('estoque_lote')
              .update({ quantidade_atual: Math.max(0, spec.quantidade_atual) })
              .eq('id_lote', Number(loteRow.id_lote));
          }
        }
      }
    }

    return {
      success: true,
      data: { id_cautela: definitiveCautelaId },
      definitiveId: definitiveCautelaId,
    };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao persistir cautela:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Synchronizes the finalization (baixa) of a Cautela to Supabase.
 * - Updates cautela status to 'Finalizada', sets data_devolucao_efetiva and operator.
 * - Updates return observations on cautela_item.
 * - Restores or updates item_patrimonio status (Disponível, Manutenção, Extraviado).
 * - Restores returned ammunition/stock quantities on estoque_lote in the database.
 */
export async function finalizarCautelaInSupabase(params: {
  id_cautela: number;
  id_operador_devolucao?: string | null;
  data_devolucao_efetiva: string;
  observacao?: string | null;
  devolucoesItens: Array<{
    id_item: number;
    status_destino: string;
    observacao_estado_devolucao?: string;
    observacao_item?: string;
  }>;
  lotesAtualizados: Array<{
    id_lote: number;
    quantidade_atual: number;
  }>;
}): Promise<SyncOperationResult> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    // 1. Update Cautela in Supabase
    const { error: cautErr } = await client
      .from('cautela')
      .update({
        status: 'Finalizada',
        data_devolucao_efetiva: params.data_devolucao_efetiva,
        id_operador_devolucao: params.id_operador_devolucao || null,
        observacao: params.observacao || null,
      })
      .eq('id_cautela', params.id_cautela);

    if (cautErr) {
      console.error('[Supabase] Falha ao atualizar status da cautela:', cautErr);
      return { success: false, error: cautErr.message, code: cautErr.code };
    }

    // 2. Update cautela_item return notes and item_patrimonio statuses
    for (const dev of params.devolucoesItens) {
      if (dev.observacao_estado_devolucao) {
        await client
          .from('cautela_item')
          .update({
            observacao_estado_devolucao: dev.observacao_estado_devolucao,
          })
          .eq('id_cautela', params.id_cautela)
          .eq('id_item', dev.id_item);
      }

      const itemPayload: any = { status: dev.status_destino };
      if (dev.observacao_item) {
        itemPayload.observacao = dev.observacao_item;
      }
      await client
        .from('item_patrimonio')
        .update(itemPayload)
        .eq('id_item', dev.id_item);
    }

    // 3. Update estoque_lote quantities with restored values
    for (const lt of params.lotesAtualizados) {
      await client
        .from('estoque_lote')
        .update({
          quantidade_atual: Math.max(0, lt.quantidade_atual),
        })
        .eq('id_lote', lt.id_lote);
    }

    return { success: true };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao finalizar cautela no banco:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Pushes a unit asset allocation (Alocação de Unidade) to Supabase.
 */
export async function pushAlocacaoToSupabase(
  alocacao: AlocacaoUnidade,
  itens: AlocacaoItem[] = []
): Promise<SyncOperationResult<{ id_alocacao: number }>> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const payload = {
      id_unidade: alocacao.id_unidade,
      id_operador: alocacao.id_operador,
      data_alocacao: alocacao.data_alocacao,
      data_devolucao_efetiva: alocacao.data_devolucao_efetiva || null,
      status: alocacao.status,
    };

    const { data: insertedAloc, error: aErr } = await client
      .from('alocacao_unidade')
      .insert(payload)
      .select()
      .single();

    if (aErr) {
      console.error('[Supabase] Falha ao inserir alocacao_unidade:', aErr);
      return { success: false, error: aErr.message, code: aErr.code };
    }

    const definitiveId = Number(insertedAloc.id_alocacao);

    for (const link of itens) {
      await client.from('alocacao_item').insert({
        id_alocacao: definitiveId,
        id_item: link.id_item,
      });

      await client
        .from('item_patrimonio')
        .update({ status: 'Alocado' })
        .eq('id_item', link.id_item);
    }

    return {
      success: true,
      data: { id_alocacao: definitiveId },
      definitiveId,
    };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao persistir alocacao:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Finalizes an asset allocation in Supabase, returning items to 'Disponível'.
 */
export async function finalizarAlocacaoInSupabase(
  id_alocacao: number,
  itensIds: number[],
  data_devolucao_efetiva: string
): Promise<SyncOperationResult> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    await client
      .from('alocacao_unidade')
      .update({
        status: 'Devolvida',
        data_devolucao_efetiva,
      })
      .eq('id_alocacao', id_alocacao);

    for (const id_item of itensIds) {
      await client
        .from('item_patrimonio')
        .update({ status: 'Disponível' })
        .eq('id_item', id_item);
    }

    return { success: true };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao finalizar alocação:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Pushes a loss/theft incident (Registro de Extravio) to Supabase.
 */
export async function pushExtravioToSupabase(extravio: RegistroExtravio): Promise<SyncOperationResult> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const payload = {
      data_fato: extravio.data_fato,
      id_policial: extravio.id_policial || null,
      id_cautela: extravio.id_cautela || null,
      numero_bo_ipm: extravio.numero_bo_ipm,
      tipo_ocorrencia: extravio.tipo_ocorrencia,
      historico_circunstanciado: extravio.historico_circunstanciado,
      providencias_adotadas: extravio.providencias_adotadas || null,
      id_operador: extravio.id_operador || null,
      dados_itens: {
        itens_extraviados: extravio.itens_extraviados,
        municoes_extraviadas: extravio.municoes_extraviadas,
      },
    };

    const { error } = await client.from('registro_extravio').insert(payload);
    if (error) {
      console.warn('[Supabase] Falha ao persistir registro_extravio:', error.message);
      return { success: false, error: error.message };
    }
    return { success: true };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}

/**
 * Pushes a shots fired incident (Registro de Disparo) to Supabase.
 */
export async function pushDisparoToSupabase(disparo: RegistroDisparo): Promise<SyncOperationResult> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const payload = {
      data_fato: disparo.data_fato,
      id_policial: disparo.id_policial,
      id_cautela: disparo.id_cautela || null,
      calibre: disparo.calibre,
      id_lote: disparo.id_lote || null,
      qtd_disparada: disparo.qtd_disparada,
      qtd_reposta: disparo.qtd_reposta,
      estojos_recolhidos: disparo.estojos_recolhidos,
      qtd_estojos_recolhidos: disparo.qtd_estojos_recolhidos || 0,
      numero_bo_ipm: disparo.numero_bo_ipm,
      local_fato: disparo.local_fato || null,
      historico_circunstanciado: disparo.historico_circunstanciado,
      id_operador: disparo.id_operador || null,
    };

    const { error } = await client.from('registro_disparo').insert(payload);
    if (error) {
      console.warn('[Supabase] Falha ao persistir registro_disparo:', error.message);
      return { success: false, error: error.message };
    }
    return { success: true };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}

/**
 * Pushes an Auditoria log to Supabase.
 * - Does not send id_auditoria on INSERT.
 * - Handles missing table gracefully.
 */
export async function pushAuditoriaToSupabase(log: AuditoriaLog): Promise<SyncOperationResult> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const { error } = await client.from('auditoria_sistema').insert({
      id_log: log.id_log || `log-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      acao: log.acao,
      tabela: log.tabela,
      id_operador: log.id_operador || null,
      operador_nome: log.operador_nome || 'Sistema SGC-6',
      detalhes: log.detalhes || {},
      data_hora: log.data_hora || new Date().toISOString(),
    });

    if (error) {
      // If table doesn't exist (PGRST125 / 42P01), don't break app flow
      if (error.code === 'PGRST125' || error.code === '42P01') {
        console.warn('[Supabase] Tabela auditoria_sistema não disponível no PostgREST cache:', error.message);
        return { success: true };
      }
      console.error('[Supabase] Falha ao persistir auditoria_sistema:', error);
      return { success: false, error: error.message, code: error.code };
    }
    return { success: true };
  } catch (err: any) {
    console.error('[Supabase] Exceção ao persistir auditoria:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Non-destructive Write Capability Test against Supabase PostgreSQL:
 * 1. Attempts non-destructive test on auditoria_sistema or fallback to unidade.
 * 2. Confirms return of data and lack of RLS / permission denial.
 */
export async function testSupabaseWriteCapability(): Promise<{
  success: boolean;
  message: string;
  latencyMs?: number;
  code?: string;
  details?: string;
}> {
  const client = getSupabaseClient();
  if (!client) {
    return { success: false, message: 'Supabase não configurado.' };
  }

  const testLogId = `test_write_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`;
  const start = performance.now();

  try {
    // 1. Try testing on auditoria_sistema
    const { error: insertErr } = await client.from('auditoria_sistema').insert({
      id_log: testLogId,
      acao: 'TESTE_CAPACIDADE_ESCRITA',
      tabela: 'sistema',
      id_operador: null,
      operador_nome: 'Teste Diagnóstico SGC-6',
      detalhes: { teste: 'Verificação não-destrutiva de permissão de escrita' },
      data_hora: new Date().toISOString(),
    });

    const latency = Math.round(performance.now() - start);

    if (!insertErr) {
      // Clean up test row
      await client.from('auditoria_sistema').delete().eq('id_log', testLogId);

      return {
        success: true,
        message: `Capacidade de escrita confirmada com sucesso (${latency}ms). O banco aceita INSERT e DELETE sem bloqueios.`,
        latencyMs: latency,
      };
    }

    // If auditoria_sistema has path / route error (PGRST125), test write on unidade as fallback
    if (insertErr.code === 'PGRST125' || insertErr.code === '42P01') {
      const tempUnitName = `__TEST_WRITE_${Date.now()}`;
      const { data: unitData, error: unitErr } = await client
        .from('unidade')
        .insert({ nome: tempUnitName, tipo_unidade: 'Setor' })
        .select('id_unidade')
        .single();

      if (!unitErr && unitData?.id_unidade) {
        await client.from('unidade').delete().eq('id_unidade', unitData.id_unidade);
        return {
          success: true,
          message: `Capacidade de escrita confirmada com sucesso via tabela de unidades (${latency}ms).`,
          latencyMs: latency,
        };
      }
    }

    console.error('[Supabase] Falha no teste de escrita:', insertErr);
    return {
      success: false,
      message: `Falha de escrita no banco: ${insertErr.message}`,
      code: insertErr.code,
      details: insertErr.details || insertErr.hint,
      latencyMs: latency,
    };
  } catch (err: any) {
    console.error('[Supabase] Exceção no teste de escrita:', err);
    return {
      success: false,
      message: `Erro na execução do teste de escrita: ${err.message}`,
    };
  }
}

export interface DiagnosticStep {
  name: string;
  category: 'connection' | 'tables' | 'permissions' | 'catalog' | 'relationships';
  status: 'pending' | 'success' | 'warning' | 'error';
  message: string;
  details?: string;
  latencyMs?: number;
}

export interface FullDiagnosticReport {
  timestamp: string;
  overallSuccess: boolean;
  canRead: boolean;
  canWrite: boolean;
  tablesFound: number;
  totalTables: number;
  steps: DiagnosticStep[];
}

/**
 * Runs a thorough 5-stage diagnostic test against the Supabase PostgreSQL database:
 * 1. Connectivity & Latency test (Read/Ping)
 * 2. Table Schema Existence (verifies all 12 core tables)
 * 3. Write/Read Permissions (tests non-destructive INSERT & DELETE)
 * 4. Structural Base Catalog (checks if basic units & item types exist)
 * 5. Identity PK & Foreign Key Validation (verifies insertion without ID and relation between item_patrimonio and detalhe_arma)
 */
export async function runSupabaseFullDiagnostics(): Promise<FullDiagnosticReport> {
  const steps: DiagnosticStep[] = [];
  const client = getSupabaseClient();

  if (!client) {
    steps.push({
      name: 'Inicialização do Cliente',
      category: 'connection',
      status: 'error',
      message: 'Supabase não está configurado. Insira a URL e a Publishable/Anon Key.',
    });
    return {
      timestamp: new Date().toISOString(),
      overallSuccess: false,
      canRead: false,
      canWrite: false,
      tablesFound: 0,
      totalTables: 12,
      steps,
    };
  }

  let canRead = false;
  let canWrite = false;
  let tablesFound = 0;
  const coreTables = [
    'unidade',
    'policial',
    'operador_sistema',
    'tipo_material',
    'item_patrimonio',
    'detalhe_arma',
    'detalhe_colete',
    'estoque_lote',
    'cautela',
    'cautela_item',
    'alocacao_unidade',
    'auditoria_sistema',
  ];

  // Stage 1: Ping & Connectivity (Read)
  const startPing = performance.now();
  try {
    const { error: pingErr } = await client.from('unidade').select('count', { count: 'exact', head: true });
    const pingLatency = Math.round(performance.now() - startPing);

    if (pingErr && pingErr.code !== '42P01' && pingErr.code !== 'PGRST116' && pingErr.code !== '42501') {
      steps.push({
        name: 'Conexão e Leitura (API REST / PostgREST)',
        category: 'connection',
        status: 'error',
        message: `Falha na conexão de leitura: ${pingErr.message}`,
        details: `Código: ${pingErr.code || 'N/A'}. Verifique se a URL do projeto e a chave estão corretas.`,
        latencyMs: pingLatency,
      });
    } else {
      steps.push({
        name: 'Conexão e Leitura (API REST / PostgREST)',
        category: 'connection',
        status: 'success',
        message: `API conectada e acessível para leitura (${pingLatency}ms)`,
        latencyMs: pingLatency,
      });
    }
  } catch (e: any) {
    steps.push({
      name: 'Conexão e Leitura',
      category: 'connection',
      status: 'error',
      message: `Erro de rede ou URL inválida: ${e.message}`,
    });
  }

  // Stage 2: Table Existence & Read Test
  const missingTables: string[] = [];
  const tableErrors: { table: string; code?: string; message: string }[] = [];
  for (const table of coreTables) {
    try {
      const { error } = await client.from(table).select('*').limit(1);
      if (error) {
        tableErrors.push({ table, code: error.code, message: error.message });
        if (
          error.code === '42P01' ||
          error.code === 'PGRST204' ||
          error.code === 'PGRST200' ||
          error.code === 'PGRST205' ||
          error.message.includes('relation') ||
          error.message.includes('does not exist') ||
          error.message.includes('schema cache')
        ) {
          missingTables.push(table);
        } else {
          tablesFound++;
        }
      } else {
        tablesFound++;
        canRead = true;
      }
    } catch (e: any) {
      missingTables.push(table);
      tableErrors.push({ table, message: e.message });
    }
  }

  if (missingTables.length === 0) {
    steps.push({
      name: 'Esquema de Tabelas (DDL no PostgreSQL)',
      category: 'tables',
      status: 'success',
      message: `Todas as 12 tabelas principais existem no PostgreSQL`,
      details: coreTables.join(', '),
    });
  } else if (tablesFound > 0) {
    steps.push({
      name: 'Esquema de Tabelas (DDL no PostgreSQL)',
      category: 'tables',
      status: 'warning',
      message: `${tablesFound} de ${coreTables.length} tabelas encontradas. Faltam: ${missingTables.join(', ')}`,
      details: 'Execute o script SQL completo no SQL Editor do Supabase.',
    });
  } else {
    steps.push({
      name: 'Esquema de Tabelas (DDL no PostgreSQL)',
      category: 'tables',
      status: 'error',
      message: 'Nenhuma tabela foi encontrada no cache do Supabase.',
      details: 'Cole e execute o Script SQL Completo no SQL Editor do Supabase.',
    });
  }

  // Stage 3: Live Non-Destructive Write Test
  const writeRes = await testSupabaseWriteCapability();
  if (writeRes.success) {
    canWrite = true;
    steps.push({
      name: 'Capacidade de Gravação Real (Escrita & Exclusão)',
      category: 'permissions',
      status: 'success',
      message: writeRes.message,
      latencyMs: writeRes.latencyMs,
    });
  } else {
    steps.push({
      name: 'Capacidade de Gravação Real (Escrita & Exclusão)',
      category: 'permissions',
      status: 'error',
      message: writeRes.message,
      details: writeRes.details ? `Detalhes: ${writeRes.details}` : undefined,
    });
  }

  // Stage 4: Base Catalog & Foreign Key Pre-requisites
  try {
    const { count: unitCount } = await client.from('unidade').select('*', { count: 'exact', head: true });
    const { count: typeCount } = await client.from('tipo_material').select('*', { count: 'exact', head: true });
    const { count: opCount } = await client.from('operador_sistema').select('*', { count: 'exact', head: true });

    if ((unitCount || 0) > 0 && (typeCount || 0) > 0) {
      steps.push({
        name: 'Catálogo Base (Unidades e Tipos de Materiais)',
        category: 'catalog',
        status: 'success',
        message: `Catálogo pronto: ${unitCount} unidade(s), ${typeCount} tipo(s) de material, ${opCount || 0} operador(es)`,
        details: 'Chaves estrangeiras (Foreign Keys) validadas para novos cadastros.',
      });
    } else {
      steps.push({
        name: 'Catálogo Base (Unidades e Tipos de Materiais)',
        category: 'catalog',
        status: 'warning',
        message: `Catálogo incompleto: ${unitCount || 0} unidades, ${typeCount || 0} tipos de materiais`,
        details: 'Execute a sincronização de dados ou o script SQL com os dados estruturais do 6º BPM.',
      });
    }
  } catch (e: any) {
    steps.push({
      name: 'Catálogo Base',
      category: 'catalog',
      status: 'warning',
      message: 'Não foi possível verificar as tabelas de catálogo base.',
      details: e.message,
    });
  }

  // Stage 5: Identity PK & Relationship Test (Armas -> DetalheArma)
  try {
    const testSerie = `TEST-DIAG-${Date.now()}`;
    // 1. Insert item_patrimonio without id_item
    const { data: testItem, error: testItemErr } = await client
      .from('item_patrimonio')
      .insert({
        modulo: 'Armas',
        tipo_item: 'Pistola',
        marca: 'Taurus',
        modelo: 'TS9',
        numero_serie: testSerie,
        status: 'Disponível',
        observacao: 'Registro temporário de validação diagnóstica',
      })
      .select()
      .single();

    if (testItemErr) {
      steps.push({
        name: 'Validação de Chave Primária IDENTITY e Relacionamento de Armas',
        category: 'relationships',
        status: 'error',
        message: `Falha ao inserir item_patrimonio sem ID: ${testItemErr.message}`,
        details: `Código: ${testItemErr.code}. Verifique se a coluna é GENERATED AS IDENTITY.`,
      });
    } else if (testItem?.id_item) {
      const generatedId = Number(testItem.id_item);

      // 2. Insert detalhe_arma with generated id_item as FK
      const { error: testDetErr } = await client.from('detalhe_arma').insert({
        id_item: generatedId,
        calibre: '9mm',
        brasao_gravado: true,
        qtd_carregadores: 3,
        carregadores_coincidem_numeracao: true,
      });

      if (testDetErr) {
        steps.push({
          name: 'Validação de Chave Primária IDENTITY e Relacionamento de Armas',
          category: 'relationships',
          status: 'error',
          message: `Item inserido (ID: ${generatedId}), mas falhou ao criar detalhe_arma: ${testDetErr.message}`,
        });
      } else {
        steps.push({
          name: 'Validação de Chave Primária IDENTITY e Relacionamento de Armas',
          category: 'relationships',
          status: 'success',
          message: `Fluxo relacional validado: item_patrimonio (ID gerado: ${generatedId}) -> detalhe_arma vinculado com sucesso`,
        });
      }

      // Cleanup test item (cascades to detalhe_arma)
      await client.from('item_patrimonio').delete().eq('id_item', generatedId);
    }
  } catch (err: any) {
    steps.push({
      name: 'Validação de Chave Primária IDENTITY e Relacionamentos',
      category: 'relationships',
      status: 'warning',
      message: `Não foi possível rodar o teste relacional completo: ${err.message}`,
    });
  }

  const overallSuccess = canRead && canWrite && tablesFound >= coreTables.length;

  return {
    timestamp: new Date().toISOString(),
    overallSuccess,
    canRead,
    canWrite,
    tablesFound,
    totalTables: coreTables.length,
    steps,
  };
}

/**
 * Gets live row counts for all main tables in the Supabase PostgreSQL database.
 */
export async function getSupabaseTableCounts(): Promise<{ success: boolean; stats?: TableStats; error?: string }> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não configurado' };

  try {
    const getCount = async (table: string): Promise<number> => {
      const { count, error } = await client.from(table).select('*', { count: 'exact', head: true });
      if (error) return 0;
      return count || 0;
    };

    const [
      unidade,
      policial,
      tipo_material,
      item_patrimonio,
      detalhe_arma,
      detalhe_colete,
      detalhe_viatura,
      detalhe_comunicacao,
      detalhe_informatica,
      estoque_lote,
      cautela,
      alocacao_unidade,
      auditoria_sistema,
    ] = await Promise.all([
      getCount('unidade'),
      getCount('policial'),
      getCount('tipo_material'),
      getCount('item_patrimonio'),
      getCount('detalhe_arma'),
      getCount('detalhe_colete'),
      getCount('detalhe_viatura'),
      getCount('detalhe_comunicacao'),
      getCount('detalhe_informatica'),
      getCount('estoque_lote'),
      getCount('cautela'),
      getCount('alocacao_unidade'),
      getCount('auditoria_sistema'),
    ]);

    return {
      success: true,
      stats: {
        unidade,
        policial,
        tipo_material,
        item_patrimonio,
        detalhe_arma,
        detalhe_colete,
        detalhe_viatura,
        detalhe_comunicacao,
        detalhe_informatica,
        estoque_lote,
        cautela,
        alocacao_unidade,
        auditoria_sistema,
      },
    };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}

/**
 * Uploads all local data to Supabase in strict dependency order:
 * 1. Unidades -> Maps local ID to DB ID
 * 2. Policiais -> Maps local ID to DB ID
 * 3. Operadores -> UUIDs linked to DB id_policial
 * 4. TiposMateriais -> Maps local ID to DB ID
 * 5. ItensPatrimonio -> Maps local ID to DB ID
 * 6. Detalhes (Armas, Coletes, IMPO, Com, Vtr, Inf) -> Linked to DB id_item
 * 7. Estoque Lotes -> Maps local ID to DB ID
 * 8. Cautelas + CautelaItens + CautelaEstoque
 * 9. Alocacoes + AlocacaoItens
 * 10. Auditoria
 */
export async function pushAllDataToSupabase(data: {
  unidades: Unidade[];
  policiais: Policial[];
  operadores: OperadorSistema[];
  tiposMateriais: TipoMaterial[];
  itens: ItemPatrimonio[];
  detalheArma: DetalheArma[];
  detalheColete: DetalheColete[];
  detalheImpo: DetalheImpo[];
  detalheComunicacao: DetalheComunicacao[];
  detalheViatura: DetalheViatura[];
  detalheInformatica: DetalheInformatica[];
  lotes: EstoqueLote[];
  cautelas: Cautela[];
  cautelaItens: CautelaItem[];
  cautelaEstoque: CautelaEstoque[];
  alocacoes: AlocacaoUnidade[];
  alocacaoItens: AlocacaoItem[];
  auditoriaLogs: AuditoriaLog[];
}): Promise<FullSyncResult> {
  const client = getSupabaseClient();
  if (!client) {
    return {
      success: false,
      message: 'Supabase não conectado',
      results: [{ entity: 'client', success: false, processed: 0, errors: 1, message: 'Cliente não configurado' }],
    };
  }

  const results: SyncEntityResult[] = [];
  const mapUnidadeId = new Map<number, number>();
  const mapPolicialId = new Map<number, number>();
  const mapTipoMaterialId = new Map<number, number>();
  const mapItemId = new Map<number, number>();
  const mapLoteId = new Map<number, number>();
  const mapCautelaId = new Map<number, number>();

  try {
    // 1. UNIDADES
    let unidadesProcessed = 0;
    let unidadesErrors = 0;
    for (const u of data.unidades) {
      const res = await pushUnidadeToSupabase(u);
      if (res.success && res.definitiveId) {
        mapUnidadeId.set(u.id_unidade, Number(res.definitiveId));
        unidadesProcessed++;
      } else {
        unidadesErrors++;
      }
    }
    results.push({
      entity: 'unidade',
      success: unidadesErrors === 0,
      processed: unidadesProcessed,
      errors: unidadesErrors,
      message: `${unidadesProcessed} unidades sincronizadas`,
    });

    // 2. TIPOS DE MATERIAL
    let tiposProcessed = 0;
    let tiposErrors = 0;
    for (const t of data.tiposMateriais) {
      const res = await pushTipoMaterialToSupabase(t);
      if (res.success && res.definitiveId) {
        mapTipoMaterialId.set(t.id_tipo_material, Number(res.definitiveId));
        tiposProcessed++;
      } else {
        tiposErrors++;
      }
    }
    results.push({
      entity: 'tipo_material',
      success: tiposErrors === 0,
      processed: tiposProcessed,
      errors: tiposErrors,
      message: `${tiposProcessed} tipos de materiais sincronizados`,
    });

    // 3. POLICIAIS
    let policiaisProcessed = 0;
    let policiaisErrors = 0;
    for (const p of data.policiais) {
      const resolvedUnit = p.id_unidade_lotacao ? mapUnidadeId.get(p.id_unidade_lotacao) || p.id_unidade_lotacao : null;
      const res = await pushPolicialToSupabase({ ...p, id_unidade_lotacao: resolvedUnit });
      if (res.success && res.definitiveId) {
        mapPolicialId.set(p.id_policial, Number(res.definitiveId));
        policiaisProcessed++;
      } else {
        policiaisErrors++;
      }
    }
    results.push({
      entity: 'policial',
      success: policiaisErrors === 0,
      processed: policiaisProcessed,
      errors: policiaisErrors,
      message: `${policiaisProcessed} policiais sincronizados`,
    });

    // 4. OPERADORES
    let opProcessed = 0;
    let opErrors = 0;
    for (const op of data.operadores) {
      const dbPolicialId = mapPolicialId.get(op.id_policial) || op.id_policial;
      const res = await pushOperadorToSupabase(op, dbPolicialId);

      if (res.success) {
        opProcessed++;
      } else {
        console.warn(`[Supabase] Erro ao sincronizar operador ${op.email}:`, res.error);
        opErrors++;
      }
    }
    results.push({
      entity: 'operador_sistema',
      success: opErrors === 0,
      processed: opProcessed,
      errors: opErrors,
      message: `${opProcessed} operadores sincronizados`,
    });

    // 5. ITENS PATRIMONIAIS & DETALHES
    let itensProcessed = 0;
    let itensErrors = 0;
    for (const it of data.itens) {
      const dbTipoId = it.id_tipo_material ? mapTipoMaterialId.get(it.id_tipo_material) || it.id_tipo_material : null;
      const arma = data.detalheArma.find((d) => d.id_item === it.id_item);
      const colete = data.detalheColete.find((d) => d.id_item === it.id_item);
      const impo = data.detalheImpo.find((d) => d.id_item === it.id_item);
      const comunicacao = data.detalheComunicacao.find((d) => d.id_item === it.id_item);
      const viatura = data.detalheViatura.find((d) => d.id_item === it.id_item);
      const informatica = data.detalheInformatica.find((d) => d.id_item === it.id_item);

      const res = await pushItemToSupabase(
        { ...it, id_tipo_material: dbTipoId },
        { arma, colete, impo, comunicacao, viatura, informatica }
      );

      if (res.success && res.definitiveId) {
        mapItemId.set(it.id_item, Number(res.definitiveId));
        itensProcessed++;
      } else {
        itensErrors++;
      }
    }
    results.push({
      entity: 'item_patrimonio',
      success: itensErrors === 0,
      processed: itensProcessed,
      errors: itensErrors,
      message: `${itensProcessed} itens patrimoniais sincronizados`,
    });

    // 6. ESTOQUE LOTES
    let lotesProcessed = 0;
    let lotesErrors = 0;
    for (const l of data.lotes) {
      const dbTipoId = l.id_tipo_material ? mapTipoMaterialId.get(l.id_tipo_material) || l.id_tipo_material : null;
      const res = await pushLoteToSupabase({ ...l, id_tipo_material: dbTipoId });
      if (res.success && res.definitiveId) {
        mapLoteId.set(l.id_lote, Number(res.definitiveId));
        lotesProcessed++;
      } else {
        lotesErrors++;
      }
    }
    results.push({
      entity: 'estoque_lote',
      success: lotesErrors === 0,
      processed: lotesProcessed,
      errors: lotesErrors,
      message: `${lotesProcessed} lotes de estoque sincronizados`,
    });

    // 7. CAUTELAS
    let cautelasProcessed = 0;
    let cautelasErrors = 0;
    for (const c of data.cautelas) {
      const dbPolicialId = mapPolicialId.get(c.id_policial) || c.id_policial;
      const linkedItens = data.cautelaItens
        .filter((ci) => ci.id_cautela === c.id_cautela)
        .map((ci) => ({
          ...ci,
          id_item: mapItemId.get(ci.id_item) || ci.id_item,
        }));
      const linkedLotes = data.cautelaEstoque
        .filter((ce) => ce.id_cautela === c.id_cautela)
        .map((ce) => ({
          ...ce,
          id_lote: mapLoteId.get(ce.id_lote) || ce.id_lote,
        }));

      const res = await pushCautelaToSupabase(
        { ...c, id_policial: dbPolicialId },
        linkedItens,
        linkedLotes
      );

      if (res.success && res.definitiveId) {
        mapCautelaId.set(c.id_cautela, Number(res.definitiveId));
        cautelasProcessed++;
      } else {
        cautelasErrors++;
      }
    }
    results.push({
      entity: 'cautela',
      success: cautelasErrors === 0,
      processed: cautelasProcessed,
      errors: cautelasErrors,
      message: `${cautelasProcessed} cautelas operacionais sincronizadas`,
    });

    const totalErrors = results.reduce((acc, r) => acc + r.errors, 0);
    const overallSuccess = totalErrors === 0;

    return {
      success: overallSuccess,
      message: overallSuccess
        ? 'Sincronização completa de todas as entidades concluída com sucesso no Supabase PostgreSQL!'
        : `Sincronização concluída com avisos/erros (${totalErrors} registro(s) com falha). Verifique o detalhamento.`,
      results,
    };
  } catch (err: any) {
    console.error('[Supabase] Exceção na sincronização completa:', err);
    return {
      success: false,
      message: `Erro fatal durante sincronização: ${err.message}`,
      results,
    };
  }
}

/**
 * Downloads all data from Supabase tables to replace/hydrate local state.
 */
export async function pullAllDataFromSupabase(): Promise<{
  success: boolean;
  data?: any;
  message?: string;
  error?: string;
}> {
  const client = getSupabaseClient();
  if (!client) return { success: false, error: 'Supabase não conectado' };

  try {
    const [
      unidadesRes,
      policiaisRes,
      operadoresRes,
      tiposRes,
      itensRes,
      armaRes,
      coleteRes,
      impoRes,
      comRes,
      vtrRes,
      infRes,
      lotesRes,
      cautelasRes,
      cautelaItensRes,
      cautelaEstoqueRes,
      alocacoesRes,
      alocacaoItensRes,
      auditoriaRes,
    ] = await Promise.all([
      client.from('unidade').select('*'),
      client.from('policial').select('*'),
      client.from('operador_sistema').select('*'),
      client.from('tipo_material').select('*'),
      client.from('item_patrimonio').select('*'),
      client.from('detalhe_arma').select('*'),
      client.from('detalhe_colete').select('*'),
      client.from('detalhe_impo').select('*'),
      client.from('detalhe_comunicacao').select('*'),
      client.from('detalhe_viatura').select('*'),
      client.from('detalhe_informatica').select('*'),
      client.from('estoque_lote').select('*'),
      client.from('cautela').select('*'),
      client.from('cautela_item').select('*'),
      client.from('cautela_estoque').select('*'),
      client.from('alocacao_unidade').select('*'),
      client.from('alocacao_item').select('*'),
      client.from('auditoria_sistema').select('*').order('data_hora', { ascending: false }).limit(50),
    ]);

    if (itensRes.error && itensRes.error.code === '42P01') {
      return {
        success: false,
        error: 'Tabelas não encontradas no Supabase. Execute o script DDL no SQL Editor primeiro.',
      };
    }

    const payload = {
      unidades: (unidadesRes.data || []).map((u) => ({
        id_unidade: Number(u.id_unidade),
        nome: u.nome,
        sigla: u.sigla,
        municipio: u.municipio,
        tipo_unidade: u.tipo_unidade,
        id_unidade_superior: u.id_unidade_superior ? Number(u.id_unidade_superior) : null,
        responsavel_nome: u.responsavel_nome,
        telefone: u.telefone,
        endereco: u.endereco,
      })),
      policiais: (policiaisRes.data || []).map((p) => {
        const unitId = p.id_unidade_lotacao != null ? Number(p.id_unidade_lotacao) : (p.id_unidade != null ? Number(p.id_unidade) : 1);
        return {
          id_policial: Number(p.id_policial),
          matricula: p.matricula,
          patente: p.patente,
          nome_guerra: p.nome_guerra,
          nome_completo: p.nome_completo,
          id_unidade_lotacao: unitId,
          id_unidade: unitId,
          status: p.status,
          contato: p.contato,
          telefone: p.telefone,
          email: p.email,
        };
      }),
      tiposMateriais: (tiposRes.data || []).map((t) => ({
        id_tipo_material: Number(t.id_tipo_material),
        nome: t.nome,
        modulo: t.modulo,
        modo_controle: t.modo_controle,
        categoria_especializada: t.categoria_especializada,
        permite_marca: Boolean(t.permite_marca),
        permite_modelo: Boolean(t.permite_modelo),
        permite_numero_serie: Boolean(t.permite_numero_serie),
        exige_numero_serie: Boolean(t.exige_numero_serie),
        permite_numero_tombo: Boolean(t.permite_numero_tombo),
        exige_numero_tombo: Boolean(t.exige_numero_tombo),
        permite_lote_validade: Boolean(t.permite_lote_validade),
        descricao: t.descricao,
        status: t.status,
      })),
      itens: (itensRes.data || []).map((i) => ({
        id_item: Number(i.id_item),
        id_tipo_material: i.id_tipo_material ? Number(i.id_tipo_material) : null,
        modulo: i.modulo,
        tipo_item: i.tipo_item,
        marca: i.marca,
        modelo: i.modelo,
        numero_serie: i.numero_serie,
        numero_tombo: i.numero_tombo,
        status: i.status,
        observacao: i.observacao,
      })),
      detalheArma: (armaRes.data || []).map((a) => ({
        id_item: Number(a.id_item),
        calibre: a.calibre,
        numero_sigma: a.numero_sigma,
        brasao_gravado: Boolean(a.brasao_gravado),
        qtd_carregadores: Number(a.qtd_carregadores),
        carregadores_coincidem_numeracao: Boolean(a.carregadores_coincidem_numeracao),
      })),
      detalheColete: (coleteRes.data || []).map((c) => ({
        id_item: Number(c.id_item),
        genero: c.genero,
        tamanho: c.tamanho,
        nivel_protecao: c.nivel_protecao,
        data_validade: c.data_validade,
      })),
      detalheImpo: (impoRes.data || []).map((im) => ({
        id_item: Number(im.id_item),
        data_validade: im.data_validade,
      })),
      detalheComunicacao: (comRes.data || []).map((cm) => ({
        id_item: Number(cm.id_item),
        imei_mac: cm.imei_mac,
        numero_linha: cm.numero_linha,
      })),
      detalheViatura: (vtrRes.data || []).map((v) => ({
        id_item: Number(v.id_item),
        placa: v.placa,
        prefixo: v.prefixo,
        renavam: v.renavam,
        chassi: v.chassi,
      })),
      detalheInformatica: (infRes.data || []).map((inf) => ({
        id_item: Number(inf.id_item),
        configuracao_resumida: inf.configuracao_resumida,
      })),
      lotes: (lotesRes.data || []).map((l) => ({
        id_lote: Number(l.id_lote),
        id_tipo_material: l.id_tipo_material ? Number(l.id_tipo_material) : null,
        modulo: l.modulo,
        tipo_item: l.tipo_item,
        marca: l.marca,
        modelo: l.modelo,
        calibre: l.calibre,
        lote_fabricacao: l.lote_fabricacao,
        data_validade: l.data_validade,
        quantidade_atual: Number(l.quantidade_atual),
        observacao: l.observacao,
      })),
      operadores: (operadoresRes.data || []).map((op) => ({
        id_operador: op.id_operador,
        id_policial: Number(op.id_policial),
        perfil_acesso: op.perfil_acesso,
        status: op.status,
        email: op.email,
        senha: op.senha || '123',
        ultimo_login: op.ultimo_login,
        criado_em: op.criado_em,
      })),
      cautelas: (cautelasRes.data || []).map((c) => ({
        id_cautela: Number(c.id_cautela),
        id_policial: Number(c.id_policial),
        id_operador_entrega: c.id_operador_entrega,
        id_operador_devolucao: c.id_operador_devolucao,
        tipo: c.tipo,
        data_retirada: c.data_retirada,
        data_prevista_devolucao: c.data_prevista_devolucao,
        data_devolucao_efetiva: c.data_devolucao_efetiva,
        status: c.status,
        observacao: c.observacao,
      })),
      cautelaItens: (cautelaItensRes.data || []).map((ci) => ({
        id_cautela: Number(ci.id_cautela),
        id_item: Number(ci.id_item),
        observacao_estado_entrega: ci.observacao_estado_entrega,
        observacao_estado_devolucao: ci.observacao_estado_devolucao,
      })),
      cautelaEstoque: (cautelaEstoqueRes.data || []).map((ce) => ({
        id_cautela: Number(ce.id_cautela),
        id_lote: Number(ce.id_lote),
        quantidade: Number(ce.quantidade),
      })),
      alocacoes: (alocacoesRes.data || []).map((a) => ({
        id_alocacao: Number(a.id_alocacao),
        id_unidade: Number(a.id_unidade),
        id_operador: a.id_operador,
        data_alocacao: a.data_alocacao,
        data_devolucao_efetiva: a.data_devolucao_efetiva,
        status: a.status,
      })),
      alocacaoItens: (alocacaoItensRes.data || []).map((ai) => ({
        id_alocacao: Number(ai.id_alocacao),
        id_item: Number(ai.id_item),
      })),
      auditoriaLogs: (auditoriaRes.data || []).map((aud) => ({
        id_log: String(aud.id_auditoria || aud.id_log || `aud-${Math.random()}`),
        acao: aud.acao,
        tabela: aud.tabela_afetada || aud.tabela || 'sistema',
        id_operador: aud.id_operador,
        operador_nome: aud.operador_nome,
        data_hora: aud.data_hora,
        detalhes: aud.detalhes_json || aud.detalhes || {},
      })),
    };

    return {
      success: true,
      data: payload,
      message: `Dados baixados com sucesso do Supabase PostgreSQL: ${payload.itens.length} itens, ${payload.policiais.length} policiais.`,
    };
  } catch (err: any) {
    return {
      success: false,
      error: `Erro ao baixar dados do Supabase: ${err.message}`,
    };
  }
}

/**
 * Realtime Subscription for automatic multi-user bidirectional sync.
 * Listens to all changes in the database (INSERT, UPDATE, DELETE) across all public tables
 * and triggers the callback with debounce.
 */
let realtimeChannelInstance: any = null;
let realtimeDebounceTimer: any = null;

export function initSupabaseRealtime(onDatabaseChanged: () => void): () => void {
  const client = getSupabaseClient();
  if (!client) return () => {};

  if (realtimeChannelInstance) {
    try {
      client.removeChannel(realtimeChannelInstance);
    } catch {}
    realtimeChannelInstance = null;
  }

  try {
    realtimeChannelInstance = client
      .channel('sgc6_live_database_changes')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
        },
        (payload: any) => {
          console.log(`[Supabase Realtime] Alteração recebida em '${payload.table}' [${payload.eventType}]`);
          if (realtimeDebounceTimer) clearTimeout(realtimeDebounceTimer);
          realtimeDebounceTimer = setTimeout(() => {
            onDatabaseChanged();
          }, 350);
        }
      )
      .subscribe((status: string, err: any) => {
        if (status === 'SUBSCRIBED') {
          console.log('[Supabase Realtime] Canal conectado com sucesso: ouvindo alterações no 6º BPM em tempo real.');
        } else if (status === 'CHANNEL_ERROR') {
          console.warn('[Supabase Realtime] Aviso no canal Realtime:', err);
        }
      });
  } catch (e) {
    console.warn('[Supabase Realtime] Não foi possível registrar listener:', e);
  }

  return () => {
    if (realtimeChannelInstance && client) {
      try {
        client.removeChannel(realtimeChannelInstance);
      } catch {}
      realtimeChannelInstance = null;
    }
  };
}

